ROOMS = {
    0x81: 'ROOM_GRANITE_WALLS',
    0x82: 'ROOM_ORIENTAL_RUG',
    0x83: 'DARK_PASSAGE',
    0x84: 'TOP_OF_PASSAGE',
    0x85: 'T_SHAPED_ROOM_1',
    0x86: 'GRAY_STONE_WALLS_1',
    0x87: 'ROUND_ROOM_HIGH_WALLS_1',
    0x88: 'TRIANGULAR_ROOM',
    0x89: 'SOUTH_END_CENTRAL_HALL',
    0x8A: 'T_SHAPED_ROOM_2',
    0x8B: 'GREY_STONE_WALLS_2',      # Two different spellings of "gray", "grey"
    0x8C: 'ROUND_ROOM_HIGH_WALLS_2',
    0x8D: 'PETITE_CHAMBER',
    0x8E: 'SMELLS_OF_DECAYING_FLESH',
    0x8F: 'TALL_ROOM',
    0x90: 'NORTH_END_CENTRAL_HALL',
    0x91: 'VAULT',
    0x92: 'ENTRANCE_LONG_DARK_TUNNEL_WEST',
    0x93: 'DARK_TUNNEL',
    0x94: 'ENTRANCE_LONG_DARK_TUNNEL_EAST',
    0x95: 'LARGE_ROOM',
    0x96: 'DENSE_DARK_DAMP_JUNGLE',
    0x97: 'DARK_DENSE_DAMP_JUNGLE',
    0x98: 'SEE_EAST_WALL',
    0x99: 'STANDS_SOUTH_WALL',
    0x9A: 'SEE_BRONZE_GATES',
    0x9B: 'SEE_NORTH_WALL',
    0x9C: 'STANDING_WEST_ENTRANCE',
    0x9D: 'AT_NORTH_WALL',
    0x9E: 'AT_EAST_WALL',
    0x9F: 'AT_SOUTH_WALL',
    0xA0: 'VERY_SMALL_ROOM',
    0xA1: 'SMALL_ROOM',
    0xA2: 'DARK_DAMP_DENSE_JUNGLE',
    0xA3: 'DENSE_DAMP_DARK_JUNGLE',
    0xA4: 'DAMP_DARK_DENSE_JUNGLE',
    0xA5: 'SECRET_PASSAGE',
    0xA6: 'END_OF_PASSAGE',
}

OBJECTS = {
    0x01: 'BOTTLE',
    0x02: 'POTION',
    0x03: 'RUG',
    0x04: 'DOOR_1',
    0x05: 'FOOD',
    0x06: 'STATUE_FACING_EAST',
    0x07: 'STATUE_FACING_WEST',
    0x08: 'RING',
    0x09: 'SWORD',
    0x0A: 'GARGOYLE_1',
    0x0B: 'ALTAR',
    0x0C: 'IDOL',
    0x0D: 'GATE',
    0x0E: 'LEVER_DROWNS',
    0x0F: 'LEVER_BEJEWELED',
    0x10: 'PLAQUE_PULL_LEVER',
    0x11: 'CANDLE_UNLIT',
    0x12: 'CANDLE_LIT',
    0x13: 'PLAQUE_INTO_TUNNEL',
    0x14: 'LAMP_BURNING',
    0x15: 'SERPENT_COILED',
    0x16: 'SERPENT_DEAD',
    0x17: 'HANDS',
    0x18: 'COIN',
    0x19: 'SLOT',
    0x1A: 'PLAQUE_FOR_PRICE',
    0x1B: 'DOOR_2',
    0x1C: 'DOOR_3',
    0x1D: 'PLAYER',
    0x1E: 'GARGOYLE_2',
    0x1F: 'GARGOYLE_3',
    0x20: 'WALL',
    0x21: 'VINE',
    0x22: 'CHOPSTICK',
    0x23: 'GUARD',
    0x24: 'GUARD_WARNING',
    0x25: 'GEM_1',
    0x26: 'GEM_2',
    0x27: 'ROOM',
    0x28: 'LAMP',
    0x29: 'FLOOR',
    0x2A: 'EXIT',
    0x2B: 'PASSAGE',
    0x2C: 'HOLE',
    0x2D: 'CORRIDOR',
    0x2E: 'CORNER',
    0x2F: 'BOW',
    0x30: 'ARROW',
    0x31: 'HALLWAY',
    0x32: 'CHAMBER',
    0x33: 'VAULT',
    0x34: 'ENTRANCE',
    0x35: 'TUNNEL',
    0x36: 'JUNGLE',
    0x37: 'TEMPLE',
    0x38: 'SERPENTS',
    0x39: 'PIT',
    0x3A: 'CEILING',
    0x3B: 'ALTAR',
    0x3C: 'AMBIENT_SOUNDS',
}

WORDS = {
    'verbs': {
        1: ['READ'],
        9: ['GET', 'TAKE', 'CARRY'],
        3: ['THROW'],
        4: ['ATTACK', 'KILL', 'HIT', 'DESTRO'],
        5: ['NORTH', 'N'],
        6: ['SOUTH', 'S'],
        7: ['EAST', 'E'],
        8: ['WEST', 'W'],
        10: ['DROP', 'PUT'],
        11: ['INVENT'],
        12: ['LOOK'],
        13: ['GIVE', 'OFFER'],
        14: ['EXAMIN', 'DESCRI', 'SEARCH'],
        15: ['OPEN'],
        16: ['PULL', 'PUSH', 'MOVE'],
        17: ['LIGHT', 'BURN', 'IGNITE'],
        18: ['EAT', 'TASTE'],
        19: ['BLOW'],
        20: ['EXTING'],
        21: ['CLIMB', 'ASCEND', 'DESCEN'],
        22: ['RUB', 'WIPE', 'POLISH'],
        23: ['DIAGNO'],
        26: ['FIND'],
        28: ['LIFT'],
        29: ['STEP'],
        31: ['WAIT', 'STAY'],
        32: ['JUMP'],
        33: ['GO', 'RUN', 'LEFT', 'RIGHT', 'ENTER'],
        35: ['KICK'],
        36: ['FEED'],
        37: ['DRINK'],
        38: ['USE'],
        39: ['SAY'],
        40: ['SCORE'],
        41: ['POUR'],
        42: ['FILL'],
        43: ['SCREAM', 'YELL'],
        45: ['QUIT', 'STOP'],
        47: ['YES'],
        48: ['NO'],
        50: ['PLUGH'],
        44: ['LEAVE'],
        52: ['PICK'],
        54: ['LOAD'],
        55: ['SAVE'],
    },
    'nouns': {
        1: ['BOTTLE'],
        3: ['POTION'],
        6: ['RUG'],
        9: ['DOOR'],
        12: ['FOOD'],
        13: ['STATUE'],
        14: ['SWORD'],
        15: ['GARGOY'],
        18: ['RING'],
        19: ['GEM'],
        22: ['LEVER'],
        24: ['PLAQUE', 'RUNES', 'SIGN', 'MESSAG'],
        25: ['CANDLE'],
        27: ['LAMP'],
        30: ['CHOPST'],
        31: ['HAND', 'HANDS'],
        32: ['COIN'],
        33: ['SLOT'],
        34: ['ALTAR'],
        35: ['IDOL'],
        36: ['SERPEN', 'SNAKE'],
        37: ['WALL', 'WALLS'],
        38: ['VINE', 'VINES'],
        39: ['GATE', 'GATES'],
        40: ['GUARD', 'GUARDS'],
        42: ['ROOM'],
        43: ['FLOOR'],
        44: ['EXIT'],
        45: ['PASSAG'],
        46: ['HOLE'],
        47: ['CORRID'],
        49: ['BOW'],
        50: ['ARROW'],
        51: ['HALLWA'],
        52: ['CHAMBE'],
        53: ['VAULT'],
        54: ['ENTRAN'],
        55: ['TUNNEL'],
        56: ['JUNGLE'],
        57: ['TEMPLE'],
        58: ['PIT'],
        59: ['CEILIN', 'ROOF'],
    },
    'prepositions': {
        1: ['TO'],
        2: ['WITH'],
        3: ['AT'],
        4: ['UNDER'],
        5: ['IN', 'INTO', 'INSIDE'],
        6: ['OUT', 'OUTSID'],
        7: ['UP'],
        8: ['DOWN'],
        9: ['OVER'],
        10: ['BEHIND'],
        11: ['AROUND'],
        12: ['ON'],
    }
}

PHRASES = {
    1: ['NORTH    *          *        *', 'NORTH     *          TO       *'],
    2: ['SOUTH    *          *        *', 'SOUTH     *          TO       *'],
    3: ['EAST     *          *        *', 'EAST      *          TO       *'],
    4: ['WEST     *          *        *', 'WEST      *          TO       *'],
    5: ['GET       ..C.....   *        *', 'PICK      *          UP       u.......', 'PICK      u.......   UP       *', 'PULL      *          OUT      u.......', 'PULL      u.......   OUT      *'],
    6: ['DROP      ..C.....   *        *', 'THROW     *          DOWN     ..C.....', 'DROP      *          DOWN     ..C.....', 'DROP      ..C.....   DOWN     *', 'DROP      ..C.....   BEHIND   u.......', 'DROP      ..C.....   UNDER    u.......', 'DROP      ..C.....   ON       u.......', 'LEAVE     ..C.....   *        *'],
    15: ['DROP      u.......   IN       u.......'],
    22: ['DROP      *          OUT      u...A...', 'BLOW      *          OUT      u...A...', 'EXTING    u...A...   *        *'],
    7: ['INVENT    *          *        *'],
    8: ['READ      .....X..   *        *'],
    9: ['ATTACK    ...P....   WITH     .v......'],
    10: ['LOOK      *          *        *', 'LOOK      *          UP       *', 'LOOK      *          DOWN     *', 'LOOK      *          OVER     u.......', 'LOOK      *          AROUND   *', 'LOOK      *          BEHIND   *'],
    11: ['LOOK      *          AT       u.......', 'EXAMIN    u.......   *        *', 'EXAMIN    *          IN       u.......', 'LOOK      u.......   OVER     *'],
    12: ['LOOK      *          UNDER    u.......'],
    16: ['LOOK      *          IN       u.......'],
    13: ['THROW     .v......   AT       ...P....'],
    57: ['THROW     u.......   IN       u.......'],
    14: ['THROW     u.......   TO       ...P....', 'GIVE      u.......   TO       ...P....'],
    17: ['OPEN      u.......   *        *'],
    58: ['OPEN      u.......   WITH     u.......'],
    18: ['PULL      u.......   *        *', 'PULL      *          DOWN     u.......'],
    45: ['PULL      *          UP       u.......', 'PULL      u.......   UP       *', 'LIFT      u.......   *        *'],
    20: ['LIGHT     u...A...   WITH     u...A...'],
    21: ['EAT       u.......   *        *'],
    23: ['CLIMB     u.......   *        *', 'CLIMB     *          UP       u.......', 'CLIMB     *          DOWN     u.......', 'CLIMB     *          OVER     u.......', 'CLIMB     *          ON       u.......', 'GO        *          UP       u.......', 'GO        *          DOWN     u.......'],
    54: ['CLIMB     *          IN       *', 'CLIMB     *          IN       u.......', 'GO        *          IN       u.......', 'JUMP      *          IN       u.......', 'STEP      *          IN       u.......'],
    55: ['CLIMB     *          OUT      *', 'CLIMB     *          OUT      u.......', 'GO        *          OUT      u.......', 'JUMP      *          OUT      u.......', 'STEP      *          OUT      u.......'],
    56: ['CLIMB     *          UNDER    u.......', 'GO        *          UNDER    u.......'],
    24: ['RUB       u.......   *        *'],
    25: ['DIAGNO    *          *        *'],
    26: ['??        *          *        *'],
    27: ['LOOK      *          AROUND   u.......'],
    28: ['LOOK      *          BEHIND   u.......'],
    29: ['LOOK      *          OUT      *'],
    30: ['YES       *          *        *'],
    31: ['NO        *          *        *'],
    33: ['PLUGH     *          *        *'],
    34: ['SCREAM    *          *        *'],
    35: ['QUIT      *          *        *'],
    37: ['LEAVE     *          *        *', 'GO        *          *        *'],
    61: ['GO        *          TO       u.......'],
    38: ['GO        *          AROUND   u.......'],
    39: ['KICK      u.......   *        *', 'KICK      *          DOWN     u.......', 'KICK      *          IN       u.......'],
    40: ['FEED      ...P....   WITH     u.......'],
    41: ['FEED      u.......   TO       ...P....'],
    42: ['USE       u.......   *        *'],
    44: ['SCORE     *          *        *'],
    47: ['WAIT      *          *        *', 'WAIT      *          AROUND   *', 'GET       *          UP       *'],
    49: ['FIND      u.......   *        *'],
    52: ['JUMP      *          OVER     u.......', 'STEP      *          OVER     u.......'],
    53: ['JUMP      *          ON       u.......', 'STEP      *          ON       u.......'],
    62: ['LOAD      *          *        *'],
    63: ['SAVE      *          *        *'],    
}

ROUTINES = {
    0x81: 'RESET_GAME',
    0x82: 'DEATH_BY_STATUE',
    0x83: 'MANIPULATE',
    0x84: 'PRINT_PERIOD',
    0x85: 'PRINT_GUARDS_MARCH_RIGHT',
    0x86: 'PRINT_GUARDS_AROUND_CORNER',
    0x87: 'PRINT_GUARDS_DISAPPEAR_LEFT',
    0x88: 'PRINT_THE_NOUN_IS_NOT_BURNING',
    0x89: 'PRINT_CANT_JUMP_THAT_FAR',
    0x8A: 'DEATH_BY_RUG_SPIKE',
    0x8B: 'DEATH_BY_HIDDEN_RUG_SPIKE',
    0x8C: 'PRINT_DISCOVER_PIT',
    0x8D: 'PRINT_STATUE_TOO_HEAVY',
    0x8E: 'PRINT_MOVE_ALTER',
    0x8F: 'ENTER_SECRET_PASSAGE', 
    0x90: 'PRINT_ALTER_MOVES_BACK',    
    0x91: 'SEAL_UP_HOLE',
    0x92: 'PRINT_SCORE',
    0x93: 'INVALID_CLIMB_IN_OR_OUT',
    0x94: 'PRINT_USE_DIRECTIONS',
    0x95: 'RESET_DUNGEON',    
}

ROUTINES = {
    0x81: 'RESET_GAME',
    0x82: 'DEATH_BY_STATUE',
    0x83: 'MANIPULATE',
    0x84: 'PRINT_PERIOD',
    0x85: 'PRINT_GUARDS_MARCH_RIGHT',
    0x86: 'PRINT_GUARDS_AROUND_CORNER',
    0x87: 'PRINT_GUARDS_DISAPPEAR_LEFT',    
    0x88: 'PRINT_THE_NOUN_IS_NOT_BURNING',    
    0x89: 'PRINT_CANT_JUMP_THAT_FAR',
    0x8A: 'DEATH_BY_RUG_SPIKE',
    0x8B: 'DEATH_BY_HIDDEN_RUG_SPIKE',
    0x8C: 'PRINT_DISCOVER_PIT',
    0x8D: 'PRINT_STATUE_TOO_HEAVY',
    0x8E: 'PRINT_MOVE_ALTER',
    0x8F: 'ENTER_SECRET_PASSAGE',
    0x90: 'PRINT_ALTER_MOVES_BACK',
    0x91: 'SEAL_UP_HOLE',
    0x92: 'PRINT_SCORE',
    0x93: 'INVALID_CLIMB_IN_OR_OUT',
    0x94: 'PRINT_USE_DIRECTIONS',
    0x95: 'RESET_DUNGEON',
    0x96: 'PRINT_GOOD_WAY_TO_LOSE_HAND',
    0x97: 'PRINT_MOUTH_IM_GAME',
    0x98: 'PRINT_GIANT_LEAP_FOR_YOU'    
}

ATTRIBUTES = {
}
