ROOMS = {
    0x81: 'MAINTENANCE_ROOM',
    0x82: 'DISPENSARY',
    0x83: 'EXAMINATION_ROOM',
    0x84: 'WEST_END_HALLWAY',
    0x85: 'PADDED_ROOM_A',
    0x86: 'PADDED_ROOM_B',
    0x87: 'EAST_WEST_HALL_A',
    0x88: 'SMALL_SQUARE_ROOM',
    0x89: 'PADDED_ROOM_C',
    0x8A: 'EAST_WEST_HALL_B',
    0x8B: 'PADDED_ROOM_D',
    0x8C: 'EAST_END_HALLWAY',
    0x8D: 'PADDED_ROOM_E',
    0x8E: 'ELECTROSHOCK_ROOM',
    0x8F: 'NORTH_END_HALLWAY',
    0x90: 'PADDED_ROOM_F',
    0x91: 'NORTH_SOUTH_HALL',
    0x92: 'KITCHEN',
    0x93: 'KENNEL',
    0x94: 'PADDED_ROOM_G',
    0x95: 'OFFICE',
    0x96: 'SOUTH_END_HALLWAY',
    0x97: 'DINING_ROOM',
    0x98: 'RECREATION_ROOM',
    0x99: 'STORAGE_SHED',
}

OBJECTS = {
    0x01: 'GREEN_DOOR_A',
    0x02: 'GREEN_DOOR_B',
    0x03: 'RED_DOOR_A',
    0x04: 'RED_DOOR_B',
    0x05: 'GREEN_DOOR_C',
    0x06: 'GREEN_DOOR_D',
    0x07: 'RED_DOOR_C',
    0x08: 'RED_DOOR_D',
    0x09: 'GREEN_DOOR_E',
    0x0A: 'GREEN_DOOR_F',
    0x0B: 'RED_DOOR_E',
    0x0C: 'GREEN_DOOR_G',
    0x0D: 'GREEN_DOOR_H',
    0x0E: 'RED_DOOR_F',
    0x0F: 'BLUE_DOOR_A',
    0x10: 'BLUE_DOOR_B',
    0x11: 'BLUE_DOOR_C',
    0x12: 'BLUE_DOOR_D',
    0x13: 'PLAYER',
    0x14: 'RED_KEY_A',
    0x15: 'BLUE_PILL_A',
    0x16: 'WINDOW_HOOK',
    0x17: 'CABINET',
    0x18: 'REFRIGERATOR',
    0x19: 'HAMBURGER_MEAT',
    0x1A: 'GUARD_DOG',
    0x1B: 'GREEN_KEY_A',
    0x1C: 'RAY_A',
    0x1D: 'RAY_B',
    0x1E: 'NAPOLEAN_A',
    0x1F: 'OBJECT_1F??',
    0x20: 'NAPOLEAN_B',
    0x21: 'OBJECT_21??',
    0x22: 'PICASSO_A',
    0x23: 'OBJECT_23??',
    0x24: 'PICASSO_B',
    0x25: 'OBJECT_25??',
    0x26: 'MERLIN_A',
    0x27: 'MERLIN_B',
    0x28: 'UNCONSCIOUS_DOCTOR_A',
    0x29: 'UNCONSCIOUS_DOCTOR_B',
    0x2A: 'HOUDINI_A',
    0x2B: 'HOUDINI_B',
    0x2C: 'HOUDINI_C',
    0x2D: 'WOMAN',
    0x2E: 'DOCTOR',
    0x2F: 'WALLS',
    0x30: 'ROOM',
    0x31: 'FLOOR',
    0x32: 'EXIT',
    0x33: 'CORNER',
    0x34: 'HALLWAY',
    0x35: 'ENTRANCE',
    0x36: 'CEILING',
    0x37: 'HANDS',
    0x38: 'SYSTEM',
    0x39: 'BLUE_PILL_B',
    0x3A: 'OBJECT_3A??',
    0x3B: 'RED_KEY_B',
    0x3C: 'DEAD_DOG',
    0x3D: 'SECRET_DOOR',
    0x3E: 'PAINTED_DOOR_A',
    0x3F: 'PAINTED_DOOR_B',
    0x40: 'GREEN_DOOR_I',
    0x41: 'GREEN_KEY_B',
    0x42: 'OBJECT_42??',
}

WORDS = {
    'verbs': {
        9: ['GET', 'GRAB', 'TAKE', 'CARRY'],
        3: ['THROW'],
        4: ['ATTACK', 'BREAK', 'KILL', 'HIT'],
        5: ['NORTH', 'N'],
        6: ['SOUTH', 'S'],
        7: ['EAST', 'E'],
        8: ['WEST', 'W'],
        10: ['DROP', 'PUT'],
        11: ['INVENT'],
        12: ['LOOK'],
        13: ['GIVE', 'OFFER'],
        14: ['EXAMIN', 'SEARCH'],
        15: ['OPEN'],
        16: ['PULL', 'PUSH', 'MOVE'],
        18: ['EAT'],
        21: ['CLIMB', 'ASCEND', 'DESCEN'],
        28: ['LIFT'],
        31: ['WAIT', 'STAY'],
        32: ['JUMP'],
        33: ['GO', 'RUN', 'LEFT', 'RIGHT', 'ENTER'],
        35: ['KICK'],
        36: ['FEED'],
        43: ['SCREAM', 'YELL'],
        45: ['QUIT', 'STOP'],
        50: ['PLUGH'],
        52: ['PICK'],
        56: ['CLOSE'],
        57: ['LOCK'],
        58: ['UNLOCK'],
        59: ['HELLO', 'HI', 'BOW', 'GREET'],
        60: ['WHAT', 'WHY', 'HOW', 'WHERE', 'WHO', 'WHEN'],
        61: ['LOWER', 'UNTIE'],
        62: ['LET'],
        63: ['COME', 'FOLLOW'],
        64: ['MEET', 'INTROD'],
    },
    'nouns': {
        22: ['KEY'],
        23: ['PILL'],
        24: ['HOOK'],
        11: ['DOOR'],
        25: ['CABINE', 'HOLE'],
        26: ['REFRIG'],
        27: ['HAMBUR', 'BURGER', 'MEAT'],
        8: ['DOG'],
        31: ['HAND', 'HANDS'],
        2: ['NAPOLE', 'BONAPA'],
        3: ['RAY', 'XRAY', 'JOHNSO'],
        4: ['HOUDIN'],
        5: ['PICASS'],
        6: ['MERLIN'],
        7: ['DOCTOR'],
        1: ['NURSE', 'THERAP'],
        37: ['WALL', 'WALLS'],
        42: ['ROOM', 'CELL', 'OFFICE', 'SHED'],
        43: ['FLOOR'],
        44: ['EXIT'],
        51: ['HALLWA'],
        54: ['ENTRAN'],
        59: ['CEILIN', 'ROOF'],
    },
    'adjectives': {
        19: ['RED'],
        20: ['GREEN'],
        21: ['BLUE'],
        61: ['SECRET'],
        62: ['PAINTE'],
    },
    'prepositions': {
        1: ['TO'],
        2: ['WITH', 'USING'],
        3: ['AT'],
        4: ['UNDER'],
        5: ['IN', 'INTO', 'INSIDE'],
        6: ['OUT', 'OUTSID'],
        7: ['UP'],
        8: ['DOWN'],
        9: ['OVER'],
        10: ['BEHIND'],
        11: ['AROUND'],
        12: ['ON'],
    }
}

PHRASES = {
    1: ['NORTH    *          *        *', 'NORTH    *          TO       *'],
    2: ['SOUTH    *          *        *', 'SOUTH    *          TO       *'],
    3: ['EAST     *          *        *', 'EAST     *          TO       *'],
    4: ['WEST     *          *        *', 'WEST     *          TO       *'],
    5: ['GET      ..C.....   *        *', 'PICK     *          UP       u.......', 'PICK     u.......   UP       *', 'PULL     *          OUT      u.......', 'PULL     u.......   OUT      *'],
    67: ['GET      ..C.....   WITH     ..C.....'],
    6: ['DROP     ..C.....   *        *', 'THROW    *          DOWN     ..C.....', 'DROP     *          DOWN     ..C.....', 'DROP     ..C.....   DOWN     *', 'DROP     ..C.....   BEHIND   u.......', 'DROP     ..C.....   UNDER    u.......', 'DROP     ..C.....   ON       u.......'],
    15: ['DROP     u.......   IN       u.......'],
    7: ['INVENT   *          *        *'],
    9: ['ATTACK   ...P....   WITH     .v......', 'ATTACK   ...P....   *        *'],
    10: ['LOOK     *          *        *', 'LOOK     *          UP       *', 'LOOK     *          DOWN     *', 'LOOK     *          OVER     u.......', 'LOOK     *          AROUND   *', 'LOOK     *          BEHIND   *'],
    11: ['LOOK     *          AT       u.......', 'EXAMIN   u.......   *        *', 'EXAMIN   *          IN       u.......', 'LOOK     u.......   OVER     *'],
    12: ['LOOK     *          UNDER    u.......'],
    16: ['LOOK     *          IN       u.......'],
    13: ['THROW    .v......   AT       ...P....'],
    57: ['THROW    u.......   IN       u.......'],
    14: ['THROW    u.......   TO       ...P....', 'GIVE     u.......   TO       ...P....'],
    17: ['OPEN     ......O.   *        *'],
    58: ['OPEN     ......O.   WITH     u.......'],
    64: ['CLOSE    ....A...   *        *'],
    65: ['LOCK     ....A...   WITH     u.......'],
    66: ['UNLOCK   .......L   WITH     u.......'],
    18: ['PULL     u.......   *        *', 'PULL     *          DOWN     u.......', 'PULL     u.......   DOWN     *'],
    45: ['PULL     *          UP       u.......', 'PULL     u.......   UP       *', 'LIFT     u.......   *        *'],
    21: ['EAT      u.......   *        *'],
    23: ['CLIMB    u.......   *        *', 'CLIMB    *          UP       u.......', 'CLIMB    *          DOWN     u.......', 'CLIMB    *          OVER     u.......', 'CLIMB    *          ON       u.......', 'GO       *          UP       u.......', 'GO       *          DOWN     u.......'],
    54: ['CLIMB    *          IN       *', 'CLIMB    *          IN       u.......', 'GO       *          IN       u.......', 'JUMP     *          IN       u.......'],
    55: ['CLIMB    *          OUT      *', 'CLIMB    *          OUT      u.......', 'GO       *          OUT      u.......', 'JUMP     *          OUT      u.......'],
    56: ['CLIMB    *          UNDER    u.......', 'GO       *          UNDER    u.......'],
    26: ['??       *          *        *'],
    27: ['LOOK     *          AROUND   u.......'],
    28: ['LOOK     *          BEHIND   u.......'],
    29: ['LOOK     *          OUT      *'],
    33: ['PLUGH    *          *        *'],
    34: ['SCREAM   *          *        *'],
    35: ['QUIT     *          *        *'],
    68: ['HELLO    *          *        *', 'HELLO    *          TO       *'],
    69: ['HELLO    ...P....   *        *', 'HELLO    *          TO       ...P....', 'HELLO    ...P....   TO       *'],
    70: ['WHAT     *          *        *'],
    71: ['WHAT     u.......   *        *'],
    37: ['GO       *          *        *'],
    61: ['GO       *          TO       u.......'],
    38: ['GO       *          AROUND   u.......'],
    39: ['KICK     u.......   *        *', 'KICK     *          DOWN     u.......', 'KICK     *          IN       u.......'],
    40: ['FEED     ...P....   WITH     u.......'],
    41: ['FEED     u.......   TO       ...P....'],
    47: ['WAIT     *          *        *', 'WAIT     *          AROUND   *', 'GET      *          UP       *'],
    52: ['JUMP     *          OVER     u.......'],
    72: ['LOWER    u.......   *        *', 'LET      u.......   DOWN     *', 'LET      *          DOWN     u.......', 'GET      *          DOWN     u.......', 'GET      u.......   DOWN     *'],
    74: ['COME     *          *        *', 'COME     *          WITH     *'],
    73: ['MEET     u.......   *        *', 'MEET     u.......   TO       u.......'],
}

ROUTINES = {
    0x81 : 'PRINT_ANOTHER_PADDED_ROOM',
    0x82 : 'PRINT_EAST_WEST_HALL',
    0x83 : 'PRINT_NORTH_SOUTH_HALL',
    0x84 : 'PRINT_SOUTH_WALL_GREEN_DOOR',
    0x85 : 'PRINT_NORTH_WALL_RED_DOOR',
    0x86 : 'PRINT_NORTH_WALL_GREEN_DOOR',
    0x87 : 'PRINT_SOUTH_WALL_RED_DOOR',
    0x88 : 'PRINT_EAST_WALL_BLUE_DOOR',
    0x89 : 'PRINT_WEST_WALL_BLUE_DOOR',
    0x8A : 'PRINT_CLOSED',
    0x8B : 'PRINT_PERIOD',
    0x8C : 'PRINT_THIS_IS_OR_YOU_ARE_IN',
    0x8D : 'PRINT_OBJECT_IS_CLOSED',
    0x8E : '', # Not given
    0x8F : '??GET_OBJECT',
    
    0x90 : '??SOMETHING_USE_DIRECTIONS',
    0x91 : 'PRINT_USE_DIRECTIONS',
    0x92 : '??YOU_CANT_DO_THAT_TO',
    0x93 : '', # Not given
    0x94 : 'INITIALIZE_GAME',
    0x95 : 'RANDOM_MOVE_AND_DROP',
    0x96 : 'PRINT_NAPOLEAN_INTRO',
    0x97 : 'PRINT_NAPOLEAN',
    0x98 : 'PRINT_PICASSO_INTRO',
    0x99 : 'PRINT_PICASSO',
    0x9A : '??COMMAND_RESPONSE',
    0x9B : '??PRINT_DIRS',
    0x9C : '??MOVE_HOUDINI_C',
    0x9D : 'PRINT_BLUE_PILL',
    0x9E : 'PRINT_OBJECT_ENTERS_ROOM',
    0x9F : 'PRINT_UNSHAVEN_MAN',
    
    0xA0 : 'PRINT_PILL_IN_HAMBURGER',
    0xA1 : 'FEED_DOG_MEAT',
    0xA2 : 'PRINT_ALREADY_HAVE_OBJECT',
    0xA3 : 'AWAKEN_IN_ROOM',
    0xA4 : 'PRINT_PICASSO_DOOR',
    0xA5 : 'ATTEMPT_CLOSE',
    0xA6 : 'ATTEMPT_OPEN',
    0xA7 : 'ATTEMPT_UNLOCK',
    0xA8 : 'PRINT_THE_FIRST_NOUN',
    0xA9 : 'PRINT_THE_SECOND_NOUN',
    0xAA : 'PRINT_THE_VAR_NAME',
    0xAB : 'ATTACK_PERSON',
    0xAC : 'PRINT_THE_VAR_NAME_(SAME_AA)',
    0xAD : 'PRINT_THE_VAR_NOT_HUNGRY',
    0xAE : 'PRINT_FIND_MOUTH_GAME',
    0xAF : 'PRINT_LEAPS_BOUNDS',
    
    0xB0 : 'PRINT_TASTES_AWEFUL',
    0xB1 : 'PRINT_YOU_GET_OBJECT_WITH_OBJECT',
    0xB2 : 'PRINT_CANT_GET_OBJECT_WITH_OBJECT',    
}

ATTRIBUTES = {

}