ROOMS = {
    0x01: 'FORYER',
    0x02: 'LIVING_ROOM',
    0x03: 'DINING_ROOM',
    0x04: 'KITCHEN',
    0x05: 'BREAKFAST_ROOM',
    0x06: 'SERVANTS_QUARTERS1',
    0x07: 'SERVANTS_QUARTERS2',
    0x08: 'DEN',
    0x09: 'EAST_END_HALL',
    0x0A: 'WEST_END_HALL',
    0x0B: 'GREEN_BEDROOM',
    0x0C: 'SECRET_PASSAGE',
    0x0D: 'BLUE_BEDROOM',
    0x0E: 'MASTER_BEDROOM',
    0x0F: 'LIBRARY',
    0x10: 'OUTSIDE_HOUSE',
}

OBJECTS = {
    0x01: 'PAPER',
    0x02: 'DOOR',
    0x03: 'KEY',
    0x04: 'FIRE',
    0x05: 'LOCKED_DOOR',
    0x06: 'KNIFE',
    0x07: 'ROPE',
    0x08: 'ARMOR',
    0x09: 'CABINET',
    0x0A: 'BUCKET',
    0x0B: 'KEY_IN_CABINET',
    0x0C: 'ROPE_CEILING',
    0x0D: 'SCROLL',
}

WORDS = {
    'verbs': {
        1: ['N'],
        2: ['E'],
        3: ['S'],
        4: ['W'],
        15: ['CLIM'],
        11: ['QUIT'],
        12: ['INVE'],
        13: ['LOOK'],
        7: ['DROP'],
        8: ['POUR'],
        6: ['GET'],
        5: ['OPEN'],
        16: ['DRIN'],
        17: ['SMAS'],
        18: ['YES'],
        19: ['NO'],
        9: ['READ'],
        14: ['PANE'],
        10: ['PLUG'],
        255: ['all']
    },
    'nouns': {
        3: ['KEY'],
        1: ['PAPE'],
        2: ['DOOR'],
        5: ['DOOR'],
        4: ['FIRE'],
        6: ['KNIF'],
        7: ['ROPE'],
        12: ['ROPE'],
        8: ['ARMO'],
        9: ['CABI'],
        11: ['CABI'],
        10: ['WATE', 'BUCK'],
        13: ['SCRO'],
    }
}
