COMMANDS_PYRAMID = {
0x01:     ['move_look',                          'room_num'],
0x02:     ['is_in_pack',                         'obj_num'],
0x03:     ['is_in_pack_or_current_room',         'obj_num'],
0x04:     ['print','ps_num'                      ],
0x05:     ['death_and_resurrect'                 ],
0x06:     None,
0x07:     ['stop_if_pass'                        ],
0x08:     ['print_score'                         ],
0x09:     ['print_score_and_endless_loop'        ],
0x0A:     ['pyramid_crawl_move_random',          'value'],
0x0B:     ['drop_object_print_ok',               'obj_num'],
0x0C:     ['move_to_room_if_was_last',           'room_num'],
0x0D:     ['is_pack_just_emerald'                ],
0x0E:     ['move_to_last_room'                   ],
0x0F:     ['print_inventory'                     ],
0x10:     ['print_room_description'              ],
0x11:     ['is_object_user_input',               'obj_num'],
0x12:     ['get_from_room_print_ok',             'obj_num'],
0x13:     None,
0x14:     ['print_ok'                            ],
0x15:     ['move_object_to_room',                'obj_num','room_num'],
0x16:     ['get_users_object_print_ok'           ],
0x17:     ['drop_users_object_print_ok'          ],
0x18:     ['move_object_to_current_room',        'obj_num'],
0x19:     ['put_object_in_container_print_ok',   'obj_num','obj_num'],
0x1A:     ['is_in_current_room',                 'obj_num'],
0x1B:     ['load_game'                           ],
0x1C:     ['save_game'                           ],
0x1D:     ['scramble_directions_print_ack'       ],
}
