import cpu.base_cpu

OPCODES = [
    {"mnemonic":"LDY #w",           "code":"108Ewmwl",         "use":"w=const",             },
    {"mnemonic":"NEG p",            "code":"00pp",             "use":"p=data_rw",           },
    {"mnemonic":"COM p",            "code":"03pp",             "use":"p=data_rw",           },
    {"mnemonic":"LSR p",            "code":"04pp",             "use":"p=data_rw",           },
    {"mnemonic":"ROR p",            "code":"06pp",             "use":"p=data_rw",           },
    {"mnemonic":"ASR p",            "code":"07pp",             "use":"p=data_rw",           },
    {"mnemonic":"LSL p",            "code":"08pp",             "use":"p=data_rw",           },
    {"mnemonic":"ASL p",            "code":"08pp",             "use":"p=data_rw",           },
    {"mnemonic":"ROL p",            "code":"09pp",             "use":"p=data_rw",           },
    {"mnemonic":"DEC p",            "code":"0App",             "use":"p=data_rw",           },
    {"mnemonic":"INC p",            "code":"0Cpp",             "use":"p=data_rw",           },
    {"mnemonic":"TST p",            "code":"0Dpp",             "use":"p=data_r",            },
    {"mnemonic":"JMP p",            "code":"0Epp",             "use":"x",            },
    {"mnemonic":"CLR p",            "code":"0Fpp",             "use":"w",            },
    {"mnemonic":"LBRN s",           "code":"1021smsl",         "use":"x",            },
    {"mnemonic":"LBHI s",           "code":"1022smsl",         "use":"x",            },
    {"mnemonic":"LBLS s",           "code":"1023smsl",         "use":"x",            },
    {"mnemonic":"LBHS s",           "code":"1024smsl",         "use":"x",            },
    {"mnemonic":"LBCC s",           "code":"1024smsl",         "use":"x",            },
    {"mnemonic":"LBLO s",           "code":"1025smsl",         "use":"x",            },
    {"mnemonic":"LBCS s",           "code":"1025smsl",         "use":"x",            },
    {"mnemonic":"LBNE s",           "code":"1026smsl",         "use":"x",            },
    {"mnemonic":"LBEQ s",           "code":"1027smsl",         "use":"x",            },
    {"mnemonic":"LBVC s",           "code":"1028smsl",         "use":"x",            },
    {"mnemonic":"LBVS s",           "code":"1029smsl",         "use":"x",            },
    {"mnemonic":"LBPL s",           "code":"102Asmsl",         "use":"x",            },
    {"mnemonic":"LBMI s",           "code":"102Bsmsl",         "use":"x",            },
    {"mnemonic":"LBGE s",           "code":"102Csmsl",         "use":"x",            },
    {"mnemonic":"LBLT s",           "code":"102Dsmsl",         "use":"x",            },
    {"mnemonic":"LBGT s",           "code":"102Esmsl",         "use":"x",            },
    {"mnemonic":"LBLE s",           "code":"102Fsmsl",         "use":"x",            },
    {"mnemonic":"SWI2",             "code":"103F",             "use":"",             },
    {"mnemonic":"CMPD #w",          "code":"1083wmwl",         "use":"",             },
    {"mnemonic":"CMPY #w",          "code":"108Cwmwl",         "use":"",             },
    {"mnemonic":"CMPD p",           "code":"1093pp",           "use":"r",            },
    {"mnemonic":"CMPY p",           "code":"109Cpp",           "use":"r",            },
    {"mnemonic":"LDY p",            "code":"109Epp",           "use":"r",            },
    {"mnemonic":"STY p",            "code":"109Fpp",           "use":"w",            },
    {"mnemonic":"CMPD y",           "code":"10A3yy",           "use":"",             },
    {"mnemonic":"CMPY y",           "code":"10ACyy",           "use":"",             },
    {"mnemonic":"LDY y",            "code":"10AEyy",           "use":"",             },
    {"mnemonic":"STY y",            "code":"10AFyy",           "use":"",             },
    {"mnemonic":"CMPD t",           "code":"10B3tmtl",         "use":"r",            },
    {"mnemonic":"CMPY t",           "code":"10BCtmtl",         "use":"r",            },
    {"mnemonic":"LDY t",            "code":"10BEtmtl",         "use":"r",            },
    {"mnemonic":"STY t",            "code":"10BFtmtl",         "use":"w",            },
    {"mnemonic":"LDS #w",           "code":"10CEwmwl",         "use":"",             },
    {"mnemonic":"LDS p",            "code":"10DEpp",           "use":"r",            },
    {"mnemonic":"STS p",            "code":"10DFpp",           "use":"w",            },
    {"mnemonic":"LDS y",            "code":"10EEyy",           "use":"",             },
    {"mnemonic":"STS y",            "code":"10EFyy",           "use":"",             },
    {"mnemonic":"LDS t",            "code":"10FEtmtl",         "use":"r",            },
    {"mnemonic":"STS t",            "code":"10FFtmtl",         "use":"w",            },
    {"mnemonic":"SWI3",             "code":"113F",             "use":"",             },
    {"mnemonic":"CMPU #w",          "code":"1183wmwl",         "use":"",             },
    {"mnemonic":"CMPS #w",          "code":"118Cwmwl",         "use":"",             },
    {"mnemonic":"CMPU p",           "code":"1193pp",           "use":"r",            },
    {"mnemonic":"CMPS p",           "code":"119Cpp",           "use":"r",            },
    {"mnemonic":"CMPU y",           "code":"11A3yy",           "use":"",             },
    {"mnemonic":"CMPS y",           "code":"11ACyy",           "use":"",             },
    {"mnemonic":"CMPU t",           "code":"11B3tmtl",         "use":"r",            },
    {"mnemonic":"CMPS t",           "code":"11BCtmtl",         "use":"r",            },
    {"mnemonic":"NOP",              "code":"12",               "use":"",             },
    {"mnemonic":"SYNC",             "code":"13",               "use":"",             },
    {"mnemonic":"LBRA s",           "code":"16smsl",           "use":"x",            },
    {"mnemonic":"LBSR s",           "code":"17smsl",           "use":"x",            },
    {"mnemonic":"DAA",              "code":"19",               "use":"",             },
    {"mnemonic":"ORCC #b",          "code":"1Abb",             "use":"",             },
    {"mnemonic":"ANDCC #b",         "code":"1Cbb",             "use":"",             },
    {"mnemonic":"SEX",              "code":"1D",               "use":"",             },
    {"mnemonic":"EXG z",            "code":"1Ezz",             "use":"",             },
    {"mnemonic":"TFR z",            "code":"1Fzz",             "use":"",             },
    {"mnemonic":"BRA r",            "code":"20rr",             "use":"x",            },
    {"mnemonic":"BRN r",            "code":"21rr",             "use":"x",            },
    {"mnemonic":"BHI r",            "code":"22rr",             "use":"x",            },
    {"mnemonic":"BLS r",            "code":"23rr",             "use":"x",            },
    {"mnemonic":"BHS r",            "code":"24rr",             "use":"x",            },
    {"mnemonic":"BCC r",            "code":"24rr",             "use":"x",            },
    {"mnemonic":"BLO r",            "code":"25rr",             "use":"x",            },
    {"mnemonic":"BCS r",            "code":"25rr",             "use":"x",            },
    {"mnemonic":"BNE r",            "code":"26rr",             "use":"x",            },
    {"mnemonic":"BEQ r",            "code":"27rr",             "use":"x",            },
    {"mnemonic":"BVC r",            "code":"28rr",             "use":"x",            },
    {"mnemonic":"BVS r",            "code":"29rr",             "use":"x",            },
    {"mnemonic":"BPL r",            "code":"2Arr",             "use":"x",            },
    {"mnemonic":"BMI r",            "code":"2Brr",             "use":"x",            },
    {"mnemonic":"BGE r",            "code":"2Crr",             "use":"x",            },
    {"mnemonic":"BLT r",            "code":"2Drr",             "use":"x",            },
    {"mnemonic":"BGT r",            "code":"2Err",             "use":"x",            },
    {"mnemonic":"BLE r",            "code":"2Frr",             "use":"x",            },
    {"mnemonic":"LEAX y",           "code":"30yy",             "use":"",             },
    {"mnemonic":"LEAY y",           "code":"31yy",             "use":"",             },
    {"mnemonic":"LEAS y",           "code":"32yy",             "use":"",             },
    {"mnemonic":"LEAU y",           "code":"33yy",             "use":"",             },
    {"mnemonic":"PSHS x",           "code":"34xx",             "use":"",             },
    {"mnemonic":"PULS q",           "code":"35qq",             "use":"",             },
    {"mnemonic":"PSHU u",           "code":"36uu",             "use":"",             },
    {"mnemonic":"PULU v",           "code":"37vv",             "use":"",             },
    {"mnemonic":"RTS",              "code":"39",               "use":"",             },
    {"mnemonic":"ABX",              "code":"3A",               "use":"",             },
    {"mnemonic":"RTI",              "code":"3B",               "use":"",             },
    {"mnemonic":"CWAI b",           "code":"3Cbb",             "use":"",             },
    {"mnemonic":"MUL",              "code":"3D",               "use":"",             },
    {"mnemonic":"RESET",            "code":"3E",               "use":"",             },
    {"mnemonic":"SWI",              "code":"3F",               "use":"",             },
    {"mnemonic":"NEGA",             "code":"40",               "use":"",             },
    {"mnemonic":"COMA",             "code":"43",               "use":"",             },
    {"mnemonic":"LSRA",             "code":"44",               "use":"",             },
    {"mnemonic":"RORA",             "code":"46",               "use":"",             },
    {"mnemonic":"ASRA",             "code":"47",               "use":"",             },
    {"mnemonic":"ASLA",             "code":"48",               "use":"",             },
    {"mnemonic":"LSLA",             "code":"48",               "use":"",             },
    {"mnemonic":"ROLA",             "code":"49",               "use":"",             },
    {"mnemonic":"DECA",             "code":"4A",               "use":"",             },
    {"mnemonic":"INCA",             "code":"4C",               "use":"",             },
    {"mnemonic":"TSTA",             "code":"4D",               "use":"",             },
    {"mnemonic":"CLRA",             "code":"4F",               "use":"",             },
    {"mnemonic":"NEGB",             "code":"50",               "use":"",             },
    {"mnemonic":"COMB",             "code":"53",               "use":"",             },
    {"mnemonic":"LSRB",             "code":"54",               "use":"",             },
    {"mnemonic":"RORB",             "code":"56",               "use":"",             },
    {"mnemonic":"ASRB",             "code":"57",               "use":"",             },
    {"mnemonic":"ASLB",             "code":"58",               "use":"",             },
    {"mnemonic":"LSLB",             "code":"58",               "use":"",             },
    {"mnemonic":"ROLB",             "code":"59",               "use":"",             },
    {"mnemonic":"DECB",             "code":"5A",               "use":"",             },
    {"mnemonic":"INCB",             "code":"5C",               "use":"",             },
    {"mnemonic":"TSTB",             "code":"5D",               "use":"",             },
    {"mnemonic":"CLRB",             "code":"5F",               "use":"",             },
    {"mnemonic":"NEG y",            "code":"60yy",             "use":"",             },
    {"mnemonic":"COM y",            "code":"63yy",             "use":"",             },
    {"mnemonic":"LSR y",            "code":"64yy",             "use":"",             },
    {"mnemonic":"ROR y",            "code":"66yy",             "use":"",             },
    {"mnemonic":"ASR y",            "code":"67yy",             "use":"",             },
    {"mnemonic":"ASL y",            "code":"68yy",             "use":"",             },
    {"mnemonic":"LSL y",            "code":"68yy",             "use":"",             },
    {"mnemonic":"ROL y",            "code":"69yy",             "use":"",             },
    {"mnemonic":"DEC y",            "code":"6Ayy",             "use":"",             },
    {"mnemonic":"INC y",            "code":"6Cyy",             "use":"",             },
    {"mnemonic":"TST y",            "code":"6Dyy",             "use":"",             },
    {"mnemonic":"JMP y",            "code":"6Eyy",             "use":"",             },
    {"mnemonic":"CLR y",            "code":"6Fyy",             "use":"",             },
    {"mnemonic":"NEG t",            "code":"70tmtl",           "use":"rw",           },
    {"mnemonic":"COM t",            "code":"73tmtl",           "use":"rw",           },
    {"mnemonic":"LSR t",            "code":"74tmtl",           "use":"rw",           },
    {"mnemonic":"ROR t",            "code":"76tmtl",           "use":"rw",           },
    {"mnemonic":"ASR t",            "code":"77tmtl",           "use":"rw",           },
    {"mnemonic":"ASL t",            "code":"78tmtl",           "use":"rw",           },
    {"mnemonic":"LSL t",            "code":"78tmtl",           "use":"rw",           },
    {"mnemonic":"ROL t",            "code":"79tmtl",           "use":"rw",           },
    {"mnemonic":"DEC t",            "code":"7Atmtl",           "use":"rw",           },
    {"mnemonic":"INC t",            "code":"7Ctmtl",           "use":"rw",           },
    {"mnemonic":"TST t",            "code":"7Dtmtl",           "use":"r",            },
    {"mnemonic":"JMP t",            "code":"7Etmtl",           "use":"x",            },
    {"mnemonic":"CLR t",            "code":"7Ftmtl",           "use":"w",            },
    {"mnemonic":"SUBA #b",          "code":"80bb",             "use":"",             },
    {"mnemonic":"CMPA #b",          "code":"81bb",             "use":"",             },
    {"mnemonic":"SBCA #b",          "code":"82bb",             "use":"",             },
    {"mnemonic":"SUBD #w",          "code":"83wmwl",           "use":"",             },
    {"mnemonic":"ANDA #b",          "code":"84bb",             "use":"",             },
    {"mnemonic":"BITA #b",          "code":"85bb",             "use":"",             },
    {"mnemonic":"LDA #b",           "code":"86bb",             "use":"",             },
    {"mnemonic":"EORA #b",          "code":"88bb",             "use":"",             },
    {"mnemonic":"ADCA #b",          "code":"89bb",             "use":"",             },
    {"mnemonic":"ORA #b",           "code":"8Abb",             "use":"",             },
    {"mnemonic":"ADDA #b",          "code":"8Bbb",             "use":"",             },
    {"mnemonic":"CMPX #w",          "code":"8Cwmwl",           "use":"",             },
    {"mnemonic":"BSR r",            "code":"8Drr",             "use":"x",            },
    {"mnemonic":"LDX #w",           "code":"8Ewmwl",           "use":"",             },
    {"mnemonic":"SUBA p",           "code":"90pp",             "use":"r",            },
    {"mnemonic":"CMPA p",           "code":"91pp",             "use":"r",            },
    {"mnemonic":"SBCA p",           "code":"92pp",             "use":"r",            },
    {"mnemonic":"SUBD p",           "code":"93pp",             "use":"r",            },
    {"mnemonic":"ANDA p",           "code":"94pp",             "use":"r",            },
    {"mnemonic":"BITA p",           "code":"95pp",             "use":"r",            },
    {"mnemonic":"LDA p",            "code":"96pp",             "use":"r",            },
    {"mnemonic":"STA p",            "code":"97pp",             "use":"w",            },
    {"mnemonic":"EORA p",           "code":"98pp",             "use":"r",            },
    {"mnemonic":"ADCA p",           "code":"99pp",             "use":"r",            },
    {"mnemonic":"ORA p",            "code":"9App",             "use":"r",            },
    {"mnemonic":"ADDA p",           "code":"9Bpp",             "use":"r",            },
    {"mnemonic":"CMPX p",           "code":"9Cpp",             "use":"r",            },
    {"mnemonic":"JSR p",            "code":"9Dpp",             "use":"x",            },
    {"mnemonic":"LDX p",            "code":"9Epp",             "use":"r",            },
    {"mnemonic":"STX p",            "code":"9Fpp",             "use":"w",            },
    {"mnemonic":"SUBA y",           "code":"A0yy",             "use":"",             },
    {"mnemonic":"CMPA y",           "code":"A1yy",             "use":"",             },
    {"mnemonic":"SBCA y",           "code":"A2yy",             "use":"",             },
    {"mnemonic":"SUBD y",           "code":"A3yy",             "use":"",             },
    {"mnemonic":"ANDA y",           "code":"A4yy",             "use":"",             },
    {"mnemonic":"BITA y",           "code":"A5yy",             "use":"",             },
    {"mnemonic":"LDA y",            "code":"A6yy",             "use":"",             },
    {"mnemonic":"STA y",            "code":"A7yy",             "use":"",             },
    {"mnemonic":"EORA y",           "code":"A8yy",             "use":"",             },
    {"mnemonic":"ADCA y",           "code":"A9yy",             "use":"",             },
    {"mnemonic":"ORA y",            "code":"AAyy",             "use":"",             },
    {"mnemonic":"ADDA y",           "code":"AByy",             "use":"",             },
    {"mnemonic":"CMPX y",           "code":"ACyy",             "use":"",             },
    {"mnemonic":"JSR y",            "code":"ADyy",             "use":"",             },
    {"mnemonic":"LDX y",            "code":"AEyy",             "use":"",             },
    {"mnemonic":"STX y",            "code":"AFyy",             "use":"",             },
    {"mnemonic":"SUBA t",           "code":"B0tmtl",           "use":"r",            },
    {"mnemonic":"CMPA t",           "code":"B1tmtl",           "use":"r",            },
    {"mnemonic":"SBCA t",           "code":"B2tmtl",           "use":"r",            },
    {"mnemonic":"SUBD t",           "code":"B3tmtl",           "use":"r",            },
    {"mnemonic":"ANDA t",           "code":"B4tmtl",           "use":"r",            },
    {"mnemonic":"BITA t",           "code":"B5tmtl",           "use":"r",            },
    {"mnemonic":"LDA t",            "code":"B6tmtl",           "use":"r",            },
    {"mnemonic":"STA t",            "code":"B7tmtl",           "use":"w",            },
    {"mnemonic":"EORA t",           "code":"B8tmtl",           "use":"r",            },
    {"mnemonic":"ADCA t",           "code":"B9tmtl",           "use":"r",            },
    {"mnemonic":"ORA t",            "code":"BAtmtl",           "use":"r",            },
    {"mnemonic":"ADDA t",           "code":"BBtmtl",           "use":"r",            },
    {"mnemonic":"CMPX t",           "code":"BCtmtl",           "use":"r",            },
    {"mnemonic":"JSR t",            "code":"BDtmtl",           "use":"x",            },
    {"mnemonic":"LDX t",            "code":"BEtmtl",           "use":"r",            },
    {"mnemonic":"STX t",            "code":"BFtmtl",           "use":"w",            },
    {"mnemonic":"SUBB #b",          "code":"C0bb",             "use":"",             },
    {"mnemonic":"CMPB #b",          "code":"C1bb",             "use":"",             },
    {"mnemonic":"SBCB #b",          "code":"C2bb",             "use":"",             },
    {"mnemonic":"ADDD #w",          "code":"C3wmwl",           "use":"",             },
    {"mnemonic":"ANDB #b",          "code":"C4bb",             "use":"",             },
    {"mnemonic":"BITB #b",          "code":"C5bb",             "use":"",             },
    {"mnemonic":"LDB #b",           "code":"C6bb",             "use":"",             },
    {"mnemonic":"EORB #b",          "code":"C8bb",             "use":"",             },
    {"mnemonic":"ADCB #b",          "code":"C9bb",             "use":"",             },
    {"mnemonic":"ORB #b",           "code":"CAbb",             "use":"",             },
    {"mnemonic":"ADDB #b",          "code":"CBbb",             "use":"",             },
    {"mnemonic":"LDD #w",           "code":"CCwmwl",           "use":"",             },
    {"mnemonic":"LDU #w",           "code":"CEwmwl",           "use":"",             },
    {"mnemonic":"SUBB p",           "code":"D0pp",             "use":"r",            },
    {"mnemonic":"CMPB p",           "code":"D1pp",             "use":"r",            },
    {"mnemonic":"SBCB p",           "code":"D2pp",             "use":"r",            },
    {"mnemonic":"ADDD p",           "code":"D3pp",             "use":"r",            },
    {"mnemonic":"ANDB p",           "code":"D4pp",             "use":"r",            },
    {"mnemonic":"BITB p",           "code":"D5pp",             "use":"r",            },
    {"mnemonic":"LDB p",            "code":"D6pp",             "use":"r",            },
    {"mnemonic":"STB p",            "code":"D7pp",             "use":"w",            },
    {"mnemonic":"EORB p",           "code":"D8pp",             "use":"",             },
    {"mnemonic":"ADCB p",           "code":"D9pp",             "use":"r",            },
    {"mnemonic":"ORB p",            "code":"DApp",             "use":"r",            },
    {"mnemonic":"ADDB p",           "code":"DBpp",             "use":"r",            },
    {"mnemonic":"LDD p",            "code":"DCpp",             "use":"r",            },
    {"mnemonic":"STD p",            "code":"DDpp",             "use":"w",            },
    {"mnemonic":"LDU p",            "code":"DEpp",             "use":"r",            },
    {"mnemonic":"STU p",            "code":"DFpp",             "use":"w",            },
    {"mnemonic":"SUBB y",           "code":"E0yy",             "use":"",             },
    {"mnemonic":"CMPB y",           "code":"E1yy",             "use":"",             },
    {"mnemonic":"SBCB y",           "code":"E2yy",             "use":"",             },
    {"mnemonic":"ADDD y",           "code":"E3yy",             "use":"",             },
    {"mnemonic":"ANDB y",           "code":"E4yy",             "use":"",             },
    {"mnemonic":"BITB y",           "code":"E5yy",             "use":"",             },
    {"mnemonic":"LDB y",            "code":"E6yy",             "use":"",             },
    {"mnemonic":"STB y",            "code":"E7yy",             "use":"",             },
    {"mnemonic":"EORB y",           "code":"E8yy",             "use":"",             },
    {"mnemonic":"ADCB y",           "code":"E9yy",             "use":"",             },
    {"mnemonic":"ORB y",            "code":"EAyy",             "use":"",             },
    {"mnemonic":"ADDB y",           "code":"EByy",             "use":"",             },
    {"mnemonic":"LDD y",            "code":"ECyy",             "use":"",             },
    {"mnemonic":"STD y",            "code":"EDyy",             "use":"",             },
    {"mnemonic":"LDU y",            "code":"EEyy",             "use":"",             },
    {"mnemonic":"STU y",            "code":"EFyy",             "use":"",             },
    {"mnemonic":"SUBB t",           "code":"F0tmtl",           "use":"r",            },
    {"mnemonic":"CMPB t",           "code":"F1tmtl",           "use":"r",            },
    {"mnemonic":"SBCB t",           "code":"F2tmtl",           "use":"r",            },
    {"mnemonic":"ADDD t",           "code":"F3tmtl",           "use":"r",            },
    {"mnemonic":"ANDB t",           "code":"F4tmtl",           "use":"r",            },
    {"mnemonic":"BITB t",           "code":"F5tmtl",           "use":"r",            },
    {"mnemonic":"LDB t",            "code":"F6tmtl",           "use":"r",            },
    {"mnemonic":"STB t",            "code":"F7tmtl",           "use":"w",            },
    {"mnemonic":"EORB t",           "code":"F8tmtl",           "use":"r",            },
    {"mnemonic":"ADCB t",           "code":"F9tmtl",           "use":"r",            },
    {"mnemonic":"ORB t",            "code":"FAtmtl",           "use":"r",            },
    {"mnemonic":"ADDB t",           "code":"FBtmtl",           "use":"r",            },
    {"mnemonic":"LDD t",            "code":"FCtmtl",           "use":"r",            },
    {"mnemonic":"STD t",            "code":"FDtmtl",           "use":"w",            },
    {"mnemonic":"LDU t",            "code":"FEtmtl",           "use":"r",            },
    {"mnemonic":"STU t",            "code":"FFtmtl",           "use":"w",            },
]

POSTS = [
    {"post":"0,X",              "code":"00",               "use":"",             },
    {"post":"1,X",              "code":"01",               "use":"",             },
    {"post":"2,X",              "code":"02",               "use":"",             },
    {"post":"3,X",              "code":"03",               "use":"",             },
    {"post":"4,X",              "code":"04",               "use":"",             },
    {"post":"5,X",              "code":"05",               "use":"",             },
    {"post":"6,X",              "code":"06",               "use":"",             },
    {"post":"7,X",              "code":"07",               "use":"",             },
    {"post":"8,X",              "code":"08",               "use":"",             },
    {"post":"9,X",              "code":"09",               "use":"",             },
    {"post":"10,X",             "code":"0A",               "use":"",             },
    {"post":"11,X",             "code":"0B",               "use":"",             },
    {"post":"12,X",             "code":"0C",               "use":"",             },
    {"post":"13,X",             "code":"0D",               "use":"",             },
    {"post":"14,X",             "code":"0E",               "use":"",             },
    {"post":"15,X",             "code":"0F",               "use":"",             },
    {"post":"-16,X",            "code":"10",               "use":"",             },
    {"post":"-15,X",            "code":"11",               "use":"",             },
    {"post":"-14,X",            "code":"12",               "use":"",             },
    {"post":"-13,X",            "code":"13",               "use":"",             },
    {"post":"-12,X",            "code":"14",               "use":"",             },
    {"post":"-11,X",            "code":"15",               "use":"",             },
    {"post":"-10,X",            "code":"16",               "use":"",             },
    {"post":"-9,X",             "code":"17",               "use":"",             },
    {"post":"-8,X",             "code":"18",               "use":"",             },
    {"post":"-7,X",             "code":"19",               "use":"",             },
    {"post":"-6,X",             "code":"1A",               "use":"",             },
    {"post":"-5,X",             "code":"1B",               "use":"",             },
    {"post":"-4,X",             "code":"1C",               "use":"",             },
    {"post":"-3,X",             "code":"1D",               "use":"",             },
    {"post":"-2,X",             "code":"1E",               "use":"",             },
    {"post":"-1,X",             "code":"1F",               "use":"",             },
    {"post":"0,Y",              "code":"20",               "use":"",             },
    {"post":"1,Y",              "code":"21",               "use":"",             },
    {"post":"2,Y",              "code":"22",               "use":"",             },
    {"post":"3,Y",              "code":"23",               "use":"",             },
    {"post":"4,Y",              "code":"24",               "use":"",             },
    {"post":"5,Y",              "code":"25",               "use":"",             },
    {"post":"6,Y",              "code":"26",               "use":"",             },
    {"post":"7,Y",              "code":"27",               "use":"",             },
    {"post":"8,Y",              "code":"28",               "use":"",             },
    {"post":"9,Y",              "code":"29",               "use":"",             },
    {"post":"10,Y",             "code":"2A",               "use":"",             },
    {"post":"11,Y",             "code":"2B",               "use":"",             },
    {"post":"12,Y",             "code":"2C",               "use":"",             },
    {"post":"13,Y",             "code":"2D",               "use":"",             },
    {"post":"14,Y",             "code":"2E",               "use":"",             },
    {"post":"15,Y",             "code":"2F",               "use":"",             },
    {"post":"-16,Y",            "code":"30",               "use":"",             },
    {"post":"-15,Y",            "code":"31",               "use":"",             },
    {"post":"-14,Y",            "code":"32",               "use":"",             },
    {"post":"-13,Y",            "code":"33",               "use":"",             },
    {"post":"-12,Y",            "code":"34",               "use":"",             },
    {"post":"-11,Y",            "code":"35",               "use":"",             },
    {"post":"-10,Y",            "code":"36",               "use":"",             },
    {"post":"-9,Y",             "code":"37",               "use":"",             },
    {"post":"-8,Y",             "code":"38",               "use":"",             },
    {"post":"-7,Y",             "code":"39",               "use":"",             },
    {"post":"-6,Y",             "code":"3A",               "use":"",             },
    {"post":"-5,Y",             "code":"3B",               "use":"",             },
    {"post":"-4,Y",             "code":"3C",               "use":"",             },
    {"post":"-3,Y",             "code":"3D",               "use":"",             },
    {"post":"-2,Y",             "code":"3E",               "use":"",             },
    {"post":"-1,Y",             "code":"3F",               "use":"",             },
    {"post":"0,U",              "code":"40",               "use":"",             },
    {"post":"1,U",              "code":"41",               "use":"",             },
    {"post":"2,U",              "code":"42",               "use":"",             },
    {"post":"3,U",              "code":"43",               "use":"",             },
    {"post":"4,U",              "code":"44",               "use":"",             },
    {"post":"5,U",              "code":"45",               "use":"",             },
    {"post":"6,U",              "code":"46",               "use":"",             },
    {"post":"7,U",              "code":"47",               "use":"",             },
    {"post":"8,U",              "code":"48",               "use":"",             },
    {"post":"9,U",              "code":"49",               "use":"",             },
    {"post":"10,U",             "code":"4A",               "use":"",             },
    {"post":"11,U",             "code":"4B",               "use":"",             },
    {"post":"12,U",             "code":"4C",               "use":"",             },
    {"post":"13,U",             "code":"4D",               "use":"",             },
    {"post":"14,U",             "code":"4E",               "use":"",             },
    {"post":"15,U",             "code":"4F",               "use":"",             },
    {"post":"-16,U",            "code":"50",               "use":"",             },
    {"post":"-15,U",            "code":"51",               "use":"",             },
    {"post":"-14,U",            "code":"52",               "use":"",             },
    {"post":"-13,U",            "code":"53",               "use":"",             },
    {"post":"-12,U",            "code":"54",               "use":"",             },
    {"post":"-11,U",            "code":"55",               "use":"",             },
    {"post":"-10,U",            "code":"56",               "use":"",             },
    {"post":"-9,U",             "code":"57",               "use":"",             },
    {"post":"-8,U",             "code":"58",               "use":"",             },
    {"post":"-7,U",             "code":"59",               "use":"",             },
    {"post":"-6,U",             "code":"5A",               "use":"",             },
    {"post":"-5,U",             "code":"5B",               "use":"",             },
    {"post":"-4,U",             "code":"5C",               "use":"",             },
    {"post":"-3,U",             "code":"5D",               "use":"",             },
    {"post":"-2,U",             "code":"5E",               "use":"",             },
    {"post":"-1,U",             "code":"5F",               "use":"",             },
    {"post":"0,S",              "code":"60",               "use":"",             },
    {"post":"1,S",              "code":"61",               "use":"",             },
    {"post":"2,S",              "code":"62",               "use":"",             },
    {"post":"3,S",              "code":"63",               "use":"",             },
    {"post":"4,S",              "code":"64",               "use":"",             },
    {"post":"5,S",              "code":"65",               "use":"",             },
    {"post":"6,S",              "code":"66",               "use":"",             },
    {"post":"7,S",              "code":"67",               "use":"",             },
    {"post":"8,S",              "code":"68",               "use":"",             },
    {"post":"9,S",              "code":"69",               "use":"",             },
    {"post":"10,S",             "code":"6A",               "use":"",             },
    {"post":"11,S",             "code":"6B",               "use":"",             },
    {"post":"12,S",             "code":"6C",               "use":"",             },
    {"post":"13,S",             "code":"6D",               "use":"",             },
    {"post":"14,S",             "code":"6E",               "use":"",             },
    {"post":"15,S",             "code":"6F",               "use":"",             },
    {"post":"-16,S",            "code":"70",               "use":"",             },
    {"post":"-15,S",            "code":"71",               "use":"",             },
    {"post":"-14,S",            "code":"72",               "use":"",             },
    {"post":"-13,S",            "code":"73",               "use":"",             },
    {"post":"-12,S",            "code":"74",               "use":"",             },
    {"post":"-11,S",            "code":"75",               "use":"",             },
    {"post":"-10,S",            "code":"76",               "use":"",             },
    {"post":"-9,S",             "code":"77",               "use":"",             },
    {"post":"-8,S",             "code":"78",               "use":"",             },
    {"post":"-7,S",             "code":"79",               "use":"",             },
    {"post":"-6,S",             "code":"7A",               "use":"",             },
    {"post":"-5,S",             "code":"7B",               "use":"",             },
    {"post":"-4,S",             "code":"7C",               "use":"",             },
    {"post":"-3,S",             "code":"7D",               "use":"",             },
    {"post":"-2,S",             "code":"7E",               "use":"",             },
    {"post":"-1,S",             "code":"7F",               "use":"",             },
    {"post":",X+",              "code":"80",               "use":"",             },
    {"post":",X++",             "code":"81",               "use":"",             },
    {"post":",-X",              "code":"82",               "use":"",             },
    {"post":",--X",             "code":"83",               "use":"",             },
    {"post":",X",               "code":"84",               "use":"",             },
    {"post":"B,X",              "code":"85",               "use":"",             },
    {"post":"A,X",              "code":"86",               "use":"",             },
    {"post":"i,X",              "code":"88ii",             "use":"",             },
    {"post":"k,X",              "code":"89kmkl",           "use":"",             },
    {"post":"D,X",              "code":"8B",               "use":"",             },
    {"post":"i,PC",             "code":"8Cii",             "use":"",             },
    {"post":"k,PC",             "code":"8Dkmkl",           "use":"",             },
    {"post":"[,X++]",           "code":"91",               "use":"",             },
    {"post":"[,--X]",           "code":"93",               "use":"",             },
    {"post":"[,X]",             "code":"94",               "use":"",             },
    {"post":"[B,X]",            "code":"95",               "use":"",             },
    {"post":"[A,X]",            "code":"96",               "use":"",             },
    {"post":"[i,X]",            "code":"98ii",             "use":"",             },
    {"post":"[k,X]",            "code":"99kmkl",           "use":"",             },
    {"post":"[D,X]",            "code":"9B",               "use":"",             },
    {"post":"[i,PC]",           "code":"9Cii",             "use":"",             },
    {"post":"[k,PC]",           "code":"9Dkmkl",           "use":"",             },
    {"post":"[t]",              "code":"9Ftmtl",           "use":"",             },
    {"post":",Y+",              "code":"A0",               "use":"",             },
    {"post":",Y++",             "code":"A1",               "use":"",             },
    {"post":",-Y",              "code":"A2",               "use":"",             },
    {"post":",--Y",             "code":"A3",               "use":"",             },
    {"post":",Y",               "code":"A4",               "use":"",             },
    {"post":"B,Y",              "code":"A5",               "use":"",             },
    {"post":"A,Y",              "code":"A6",               "use":"",             },
    {"post":"i,Y",              "code":"A8ii",             "use":"",             },
    {"post":"k,Y",              "code":"A9kmkl",           "use":"",             },
    {"post":"D,Y",              "code":"AB",               "use":"",             },
    {"post":"i,PC",             "code":"ACii",             "use":"",             },
    {"post":"k,PC",             "code":"ADkmkl",           "use":"",             },
    {"post":"[,Y++]",           "code":"B1",               "use":"",             },
    {"post":"[,--Y]",           "code":"B3",               "use":"",             },
    {"post":"[,Y]",             "code":"B4",               "use":"",             },
    {"post":"[B,Y]",            "code":"B5",               "use":"",             },
    {"post":"[A,Y]",            "code":"B6",               "use":"",             },
    {"post":"[i,Y]",            "code":"B8ii",             "use":"",             },
    {"post":"[k,Y]",            "code":"B9kmkl",           "use":"",             },
    {"post":"[D,Y]",            "code":"BB",               "use":"",             },
    {"post":"[i,PC]",           "code":"BCii",             "use":"",             },
    {"post":"[k,PC]",           "code":"BDkmkl",           "use":"",             },
    {"post":"[t]",              "code":"BFtmtl",           "use":"",             },
    {"post":",U+",              "code":"C0",               "use":"",             },
    {"post":",U++",             "code":"C1",               "use":"",             },
    {"post":",-U",              "code":"C2",               "use":"",             },
    {"post":",--U",             "code":"C3",               "use":"",             },
    {"post":",U",               "code":"C4",               "use":"",             },
    {"post":"B,U",              "code":"C5",               "use":"",             },
    {"post":"A,U",              "code":"C6",               "use":"",             },
    {"post":"i,U",              "code":"C8ii",             "use":"",             },
    {"post":"k,U",              "code":"C9kmkl",           "use":"",             },
    {"post":"D,U",              "code":"CB",               "use":"",             },
    {"post":"i,PC",             "code":"CCii",             "use":"",             },
    {"post":"k,PC",             "code":"CDkmkl",           "use":"",             },
    {"post":"[,U++]",           "code":"D1",               "use":"",             },
    {"post":"[,--U]",           "code":"D3",               "use":"",             },
    {"post":"[,U]",             "code":"D4",               "use":"",             },
    {"post":"[B,U]",            "code":"D5",               "use":"",             },
    {"post":"[A,U]",            "code":"D6",               "use":"",             },
    {"post":"[i,U]",            "code":"D8ii",             "use":"",             },
    {"post":"[k,U]",            "code":"D9kmkl",           "use":"",             },
    {"post":"[D,U]",            "code":"DB",               "use":"",             },
    {"post":"[i,PC]",           "code":"DCii",             "use":"",             },
    {"post":"[k,PC]",           "code":"DDkmkl",           "use":"",             },
    {"post":"[t]",              "code":"DFtmtl",           "use":"",             },
    {"post":",S+",              "code":"E0",               "use":"",             },
    {"post":",S++",             "code":"E1",               "use":"",             },
    {"post":",-S",              "code":"E2",               "use":"",             },
    {"post":",--S",             "code":"E3",               "use":"",             },
    {"post":",S",               "code":"E4",               "use":"",             },
    {"post":"B,S",              "code":"E5",               "use":"",             },
    {"post":"A,S",              "code":"E6",               "use":"",             },
    {"post":"i,S",              "code":"E8ii",             "use":"",             },
    {"post":"k,S",              "code":"E9kmkl",           "use":"",             },
    {"post":"i,X",              "code":"EAii",             "use":"",             },
    {"post":"D,S",              "code":"EB",               "use":"",             },
    {"post":"i,PC",             "code":"ECii",             "use":"",             },
    {"post":"k,PC",             "code":"EDkmkl",           "use":"",             },
    {"post":"[,S++]",           "code":"F1",               "use":"",             },
    {"post":"[,--S]",           "code":"F3",               "use":"",             },
    {"post":"[,S]",             "code":"F4",               "use":"",             },
    {"post":"[B,S]",            "code":"F5",               "use":"",             },
    {"post":"[A,S]",            "code":"F6",               "use":"",             },
    {"post":"[i,S]",            "code":"F8ii",             "use":"",             },
    {"post":"[k,S]",            "code":"F9kmkl",           "use":"",             },
    {"post":"[D,S]",            "code":"FB",               "use":"",             },
    {"post":"[i,PC]",           "code":"FCii",             "use":"",             },
    {"post":"[k,PC]",           "code":"FDkmkl",           "use":"",             },
    {"post":"[t]",              "code":"FFtmtl",           "use":"",             },
]

# TODO: LDA $FF00,PC ; PC relative


class CPU_6809(cpu.base_cpu.CPU):

    def __init__(self):

        expanded_opcodes = []

        # Expand the "post" mnemonics
        for entry in OPCODES:
            if 'y' in entry['mnemonic']:
                for post in POSTS:
                    new_mnem = entry['mnemonic'].replace('y', post['post'])
                    new_code = entry['code'].replace('yy', post['code'])
                    new_entry = {'mnemonic': new_mnem,
                                 # 'code': new_code, 'bus': entry['bus']}
                                 'code': new_code, 'use': ''}
                    expanded_opcodes.append(new_entry)
            else:
                expanded_opcodes.append(entry)

        super().__init__(expanded_opcodes)
