import cpu.base_cpu

OPCODES = [
    {"mnemonic": "NOP", "code": "01", "use": ""},
    {"mnemonic": "LSRD", "code": "04", "use": ""},
    {"mnemonic": "TAP", "code": "06", "use": ""},
    {"mnemonic": "TPA", "code": "07", "use": ""},
    {"mnemonic": "INX", "code": "08", "use": ""},
    {"mnemonic": "DEX", "code": "09", "use": ""},
    {"mnemonic": "CLV", "code": "0A", "use": ""},
    {"mnemonic": "SEV", "code": "0B", "use": ""},
    {"mnemonic": "CLC", "code": "0C", "use": ""},
    {"mnemonic": "SEC", "code": "0D", "use": ""},
    {"mnemonic": "CLI", "code": "0E", "use": ""},
    {"mnemonic": "SEI", "code": "0F", "use": ""},
    {"mnemonic": "SBA", "code": "10", "use": ""},
    {"mnemonic": "CBA", "code": "11", "use": ""},
    {"mnemonic": "TAB", "code": "16", "use": ""},
    {"mnemonic": "TBA", "code": "17", "use": ""},
    {"mnemonic": "DAA", "code": "19", "use": ""},
    {"mnemonic": "ABA", "code": "1B", "use": ""},
    {"mnemonic": "BRA r", "code": "20rr", "use": "x"},
    {"mnemonic": "BRN r", "code": "21rr", "use": "x"},
    {"mnemonic": "BHI r", "code": "22rr", "use": "x"},
    {"mnemonic": "BLS r", "code": "23rr", "use": "x"},
    {"mnemonic": "BCC r", "code": "24rr", "use": "x"},
    {"mnemonic": "BHS r", "code": "24rr", "use": "x"},
    {"mnemonic": "BCC r", "code": "24rr", "use": "x"},
    {"mnemonic": "BLO r", "code": "25rr", "use": "x"},
    {"mnemonic": "BNE r", "code": "26rr", "use": "x"},
    {"mnemonic": "BEQ r", "code": "27rr", "use": "x"},
    {"mnemonic": "BVC r", "code": "28rr", "use": "x"},
    {"mnemonic": "BVS r", "code": "29rr", "use": "x"},
    {"mnemonic": "BPL r", "code": "2Arr", "use": "x"},
    {"mnemonic": "BMI r", "code": "2Brr", "use": "x"},
    {"mnemonic": "BGE r", "code": "2Crr", "use": "x"},
    {"mnemonic": "BLT r", "code": "2Drr", "use": "x"},
    {"mnemonic": "BGT r", "code": "2Err", "use": "x"},
    {"mnemonic": "BLE r", "code": "2Frr", "use": "x"},
    {"mnemonic": "TSX", "code": "30", "use": ""},
    {"mnemonic": "INS", "code": "31", "use": ""},
    {"mnemonic": "PULA", "code": "32", "use": ""},
    {"mnemonic": "PULB", "code": "33", "use": ""},
    {"mnemonic": "DES", "code": "34", "use": ""},
    {"mnemonic": "TXS", "code": "35", "use": ""},
    {"mnemonic": "PSHA", "code": "36", "use": ""},
    {"mnemonic": "PSHB", "code": "37", "use": ""},
    {"mnemonic": "PULX", "code": "38", "use": ""},
    {"mnemonic": "RTS", "code": "39", "use": ""},
    {"mnemonic": "ABX", "code": "3A", "use": ""},
    {"mnemonic": "RTI", "code": "3B", "use": ""},
    {"mnemonic": "PSHX", "code": "3C", "use": ""},
    {"mnemonic": "MUL", "code": "3D", "use": ""},
    {"mnemonic": "WAI", "code": "3E", "use": ""},
    {"mnemonic": "SWI", "code": "3F", "use": ""},
    {"mnemonic": "NEGA", "code": "40", "use": ""},
    {"mnemonic": "COMA", "code": "43", "use": ""},
    {"mnemonic": "LSRA", "code": "44", "use": ""},
    {"mnemonic": "RORA", "code": "46", "use": ""},
    {"mnemonic": "ASRA", "code": "47", "use": ""},
    {"mnemonic": "LSLA", "code": "48", "use": ""},
    {"mnemonic": "ASLA", "code": "48", "use": ""},
    {"mnemonic": "ROLA", "code": "49", "use": ""},
    {"mnemonic": "DECA", "code": "4A", "use": ""},
    {"mnemonic": "INCA", "code": "4C", "use": ""},
    {"mnemonic": "TSTA", "code": "4D", "use": ""},
    {"mnemonic": "CLRA", "code": "4F", "use": ""},
    {"mnemonic": "NEGB", "code": "50", "use": ""},
    {"mnemonic": "COMB", "code": "53", "use": ""},
    {"mnemonic": "LSRB", "code": "54", "use": ""},
    {"mnemonic": "RORB", "code": "56", "use": ""},
    {"mnemonic": "ASRB", "code": "57", "use": ""},
    {"mnemonic": "LSLB", "code": "58", "use": ""},
    {"mnemonic": "ASLB", "code": "58", "use": ""},
    {"mnemonic": "ROLB", "code": "59", "use": ""},
    {"mnemonic": "DECB", "code": "5A", "use": ""},
    {"mnemonic": "INCB", "code": "5C", "use": ""},
    {"mnemonic": "TSTB", "code": "5D", "use": ""},
    {"mnemonic": "CLRB", "code": "5F", "use": ""},
    {"mnemonic": "NEG i,X", "code": "60ii", "use": ""},
    {"mnemonic": "COM i,X", "code": "63ii", "use": ""},
    {"mnemonic": "LSR i,X", "code": "64ii", "use": ""},
    {"mnemonic": "ROR i,X", "code": "66ii", "use": ""},
    {"mnemonic": "ASR i,X", "code": "67ii", "use": ""},
    {"mnemonic": "ASL i,X", "code": "68ii", "use": ""},
    {"mnemonic": "LSL i,X", "code": "68ii", "use": ""},
    {"mnemonic": "ROL i,X", "code": "69ii", "use": ""},
    {"mnemonic": "DEC i,X", "code": "6Aii", "use": ""},
    {"mnemonic": "INC i,X", "code": "6Cii", "use": ""},
    {"mnemonic": "TST i,X", "code": "6Dii", "use": ""},
    {"mnemonic": "JMP i,X", "code": "6Eii", "use": ""},
    {"mnemonic": "CLR i,X", "code": "6Fii", "use": ""},
    {"mnemonic": "NEG t", "code": "70tmtl", "use": "rw"},
    {"mnemonic": "COM t", "code": "73tmtl", "use": "rw"},
    {"mnemonic": "LSR t", "code": "74tmtl", "use": "rw"},
    {"mnemonic": "ROR t", "code": "76tmtl", "use": "rw"},
    {"mnemonic": "ASR t", "code": "77tmtl", "use": "rw"},
    {"mnemonic": "ASL t", "code": "78tmtl", "use": "rw"},
    {"mnemonic": "LSL t", "code": "78tmtl", "use": "rw"},
    {"mnemonic": "ROL t", "code": "79tmtl", "use": "rw"},
    {"mnemonic": "DEC t", "code": "7Atmtl", "use": "rw"},
    {"mnemonic": "INC t", "code": "7Ctmtl", "use": "rw"},
    {"mnemonic": "TST t", "code": "7Dtmtl", "use": "r"},
    {"mnemonic": "JMP t", "code": "7Etmtl", "use": "x"},
    {"mnemonic": "CLR t", "code": "7Ftmtl", "use": "r"},
    {"mnemonic": "SUBA #b", "code": "80bb", "use": ""},
    {"mnemonic": "CMPA #b", "code": "81bb", "use": ""},
    {"mnemonic": "SBCA #b", "code": "82bb", "use": ""},
    {"mnemonic": "SUBD #w", "code": "83wmwl", "use": ""},
    {"mnemonic": "ANDA #b", "code": "84bb", "use": ""},
    {"mnemonic": "BITA #b", "code": "85bb", "use": ""},
    {"mnemonic": "LDA #b", "code": "86bb", "use": ""},
    {"mnemonic": "EORA #b", "code": "88bb", "use": ""},
    {"mnemonic": "ADCA #b", "code": "89bb", "use": ""},
    {"mnemonic": "ORA #b", "code": "8Abb", "use": ""},
    {"mnemonic": "ADDA #b", "code": "8Bbb", "use": ""},
    {"mnemonic": "CPX #w", "code": "8Cwmwl", "use": ""},
    {"mnemonic": "BSR r", "code": "8Drr", "use": "x"},
    {"mnemonic": "LDS #w", "code": "8Ewmwl", "use": ""},
    {"mnemonic": "SUBA p", "code": "90pp", "use": "r"},
    {"mnemonic": "CMPA p", "code": "91pp", "use": "r"},
    {"mnemonic": "SBCA p", "code": "92pp", "use": "r"},
    {"mnemonic": "SUBD p", "code": "93pp", "use": "r"},
    {"mnemonic": "ANDA p", "code": "94pp", "use": "r"},
    {"mnemonic": "BITA p", "code": "95pp", "use": "r"},
    {"mnemonic": "LDA p", "code": "96pp", "use": "r"},
    {"mnemonic": "STA p", "code": "97pp", "use": "w"},
    {"mnemonic": "EORA p", "code": "98pp", "use": "r"},
    {"mnemonic": "ADCA p", "code": "99pp", "use": "r"},
    {"mnemonic": "ORA p", "code": "9App", "use": "r"},
    {"mnemonic": "ADDA p", "code": "9Bpp", "use": "r"},
    {"mnemonic": "CPX p", "code": "9Cpp", "use": "r"},
    {"mnemonic": "JSR p", "code": "9Dpp", "use": "x"},
    {"mnemonic": "LDS p", "code": "9Epp", "use": "r"},
    {"mnemonic": "STS p", "code": "9Fpp", "use": "w"},
    {"mnemonic": "SUBA i,X", "code": "A0ii", "use": ""},
    {"mnemonic": "CMPA i,X", "code": "A1ii", "use": ""},
    {"mnemonic": "SBCA i,X", "code": "A2ii", "use": ""},
    {"mnemonic": "SUBD i,X", "code": "A3ii", "use": ""},
    {"mnemonic": "ANDA i,X", "code": "A4ii", "use": ""},
    {"mnemonic": "BITA i,X", "code": "A5ii", "use": ""},
    {"mnemonic": "LDA i,X", "code": "A6ii", "use": ""},
    {"mnemonic": "STA i,X", "code": "A7ii", "use": ""},
    {"mnemonic": "EORA i,X", "code": "A8ii", "use": ""},
    {"mnemonic": "ADCA i,X", "code": "A9ii", "use": ""},
    {"mnemonic": "ORA i,X", "code": "AAii", "use": ""},
    {"mnemonic": "ADDA i,X", "code": "ABii", "use": ""},
    {"mnemonic": "CPX i,X", "code": "ACii", "use": ""},
    {"mnemonic": "JSR i,X", "code": "ADii", "use": ""},
    {"mnemonic": "LDS i,X", "code": "AEii", "use": ""},
    {"mnemonic": "STS i,X", "code": "AFii", "use": ""},
    {"mnemonic": "SUBA t", "code": "B0tmtl", "use": "r"},
    {"mnemonic": "CMPA t", "code": "B1tmtl", "use": "r"},
    {"mnemonic": "SBCA t", "code": "B2tmtl", "use": "r"},
    {"mnemonic": "SUBD t", "code": "B3tmtl", "use": "r"},
    {"mnemonic": "ANDA t", "code": "B4tmtl", "use": "r"},
    {"mnemonic": "BITA t", "code": "B5tmtl", "use": "r"},
    {"mnemonic": "LDA t", "code": "B6tmtl", "use": "r"},
    {"mnemonic": "STA t", "code": "B7tmtl", "use": "w"},
    {"mnemonic": "EORA t", "code": "B8tmtl", "use": "r"},
    {"mnemonic": "ADCA t", "code": "B9tmtl", "use": "r"},
    {"mnemonic": "ORA t", "code": "BAtmtl", "use": "r"},
    {"mnemonic": "ADDA t", "code": "BBtmtl", "use": "r"},
    {"mnemonic": "CPX t", "code": "BCtmtl", "use": "r"},
    {"mnemonic": "JSR t", "code": "BDtmtl", "use": "x"},
    {"mnemonic": "LDS t", "code": "BEtmtl", "use": "r"},
    {"mnemonic": "STS t", "code": "BFtmtl", "use": "w"},
    {"mnemonic": "SUBB #b", "code": "C0bb", "use": ""},
    {"mnemonic": "CMPB #b", "code": "C1bb", "use": ""},
    {"mnemonic": "SBCB #b", "code": "C2bb", "use": ""},
    {"mnemonic": "ADDD #w", "code": "C3wmwl", "use": ""},
    {"mnemonic": "ANDB #b", "code": "C4bb", "use": ""},
    {"mnemonic": "BITB #b", "code": "C5bb", "use": ""},
    {"mnemonic": "LDB #b", "code": "C6bb", "use": ""},
    {"mnemonic": "EORB #b", "code": "C8bb", "use": ""},
    {"mnemonic": "ADCB #b", "code": "C9bb", "use": ""},
    {"mnemonic": "ORB #b", "code": "CAbb", "use": ""},
    {"mnemonic": "ADDB #b", "code": "CBbb", "use": ""},
    {"mnemonic": "LDD #w", "code": "CCwmwl", "use": ""},
    {"mnemonic": "LDX #w", "code": "CEwmwl", "use": ""},
    {"mnemonic": "SUBB p", "code": "D0pp", "use": "r"},
    {"mnemonic": "CMPB p", "code": "D1pp", "use": "r"},
    {"mnemonic": "SBCB p", "code": "D2pp", "use": "r"},
    {"mnemonic": "ADDD p", "code": "D3pp", "use": "r"},
    {"mnemonic": "ANDB p", "code": "D4pp", "use": "r"},
    {"mnemonic": "BITB p", "code": "D5pp", "use": "r"},
    {"mnemonic": "LDB p", "code": "D6pp", "use": "r"},
    {"mnemonic": "STB p", "code": "D7pp", "use": "w"},
    {"mnemonic": "EORB p", "code": "D8pp", "use": "r"},
    {"mnemonic": "ADCB p", "code": "D9pp", "use": "r"},
    {"mnemonic": "ORB p", "code": "DApp", "use": "r"},
    {"mnemonic": "ADDB p", "code": "DBpp", "use": "r"},
    {"mnemonic": "LDD p", "code": "DCpp", "use": "r"},
    {"mnemonic": "STD p", "code": "DDpp", "use": "w"},
    {"mnemonic": "LDX p", "code": "DEpp", "use": "r"},
    {"mnemonic": "STX p", "code": "DFpp", "use": "r"},
    {"mnemonic": "SUBB i,X", "code": "E0ii", "use": ""},
    {"mnemonic": "CMPB i,X", "code": "E1ii", "use": ""},
    {"mnemonic": "SBCB i,X", "code": "E2ii", "use": ""},
    {"mnemonic": "ADDD i,X", "code": "E3ii", "use": ""},
    {"mnemonic": "ANDB i,X", "code": "E4ii", "use": ""},
    {"mnemonic": "BITB i,X", "code": "E5ii", "use": ""},
    {"mnemonic": "LDB i,X", "code": "E6ii", "use": ""},
    {"mnemonic": "STB i,X", "code": "E7ii", "use": ""},
    {"mnemonic": "EORB i,X", "code": "E8ii", "use": ""},
    {"mnemonic": "ADCB i,X", "code": "E9ii", "use": ""},
    {"mnemonic": "ORB i,X", "code": "EAii", "use": ""},
    {"mnemonic": "ADDB i,X", "code": "EBii", "use": ""},
    {"mnemonic": "LDD i,X", "code": "ECii", "use": ""},
    {"mnemonic": "STD i,X", "code": "EDpp", "use": ""},
    {"mnemonic": "LDX i,X", "code": "EEii", "use": ""},
    {"mnemonic": "STX i,X", "code": "EFii", "use": ""},
    {"mnemonic": "SUBB t", "code": "F0tmtl", "use": "r"},
    {"mnemonic": "CMPB t", "code": "F1tmtl", "use": "r"},
    {"mnemonic": "SBCB t", "code": "F2tmtl", "use": "r"},
    {"mnemonic": "ADDD t", "code": "F3tmtl", "use": "r"},
    {"mnemonic": "ANDB t", "code": "F4tmtl", "use": "r"},
    {"mnemonic": "BITB t", "code": "F5tmtl", "use": "r"},
    {"mnemonic": "LDB t", "code": "F6tmtl", "use": "r"},
    {"mnemonic": "STB t", "code": "F7tmtl", "use": "w"},
    {"mnemonic": "EORB t", "code": "F8tmtl", "use": "r"},
    {"mnemonic": "ADCB t", "code": "F9tmtl", "use": "r"},
    {"mnemonic": "ORB t", "code": "FAtmtl", "use": "r"},
    {"mnemonic": "ADDB t", "code": "FBtmtl", "use": "r"},
    {"mnemonic": "LDD t", "code": "FCtmtl", "use": "r"},
    {"mnemonic": "STD t", "code": "FDtmtl", "use": "w"},
    {"mnemonic": "LDX t", "code": "FEtmtl", "use": "r"},
    {"mnemonic": "STX t", "code": "FFtmtl", "use": "w"}
]


class CPU_6803(cpu.base_cpu.CPU):

    def __init__(self):
        super().__init__(OPCODES)
