import cpu.base_cpu

OPCODES = [
    {"mnem": "LDY #w", "code": "108Ewmwl", "bus": ""},
    {"mnem": "NEG p", "code": "00pp", "bus": "rw"},
    {"mnem": "COM p", "code": "03pp", "bus": "rw"},
    {"mnem": "LSR p", "code": "04pp", "bus": "rw"},
    {"mnem": "ROR p", "code": "06pp", "bus": "rw"},
    {"mnem": "ASR p", "code": "07pp", "bus": "rw"},
    {"mnem": "LSL p", "code": "08pp", "bus": "rw"},
    {"mnem": "ASL p", "code": "08pp", "bus": "rw"},
    {"mnem": "ROL p", "code": "09pp", "bus": "rw"},
    {"mnem": "DEC p", "code": "0App", "bus": "rw"},
    {"mnem": "INC p", "code": "0Cpp", "bus": "rw"},
    {"mnem": "TST p", "code": "0Dpp", "bus": "r"},
    {"mnem": "JMP p", "code": "0Epp", "bus": "x"},
    {"mnem": "CLR p", "code": "0Fpp", "bus": "w"},
    {"mnem": "LBRN s", "code": "1021smsl", "bus": "x"},
    {"mnem": "LBHI s", "code": "1022smsl", "bus": "x"},
    {"mnem": "LBLS s", "code": "1023smsl", "bus": "x"},
    {"mnem": "LBHS s", "code": "1024smsl", "bus": "x"},
    {"mnem": "LBCC s", "code": "1024smsl", "bus": "x"},
    {"mnem": "LBLO s", "code": "1025smsl", "bus": "x"},
    {"mnem": "LBCS s", "code": "1025smsl", "bus": "x", "alias": "LBLO s"},
    {"mnem": "LBNE s", "code": "1026smsl", "bus": "x"},
    {"mnem": "LBEQ s", "code": "1027smsl", "bus": "x"},
    {"mnem": "LBVC s", "code": "1028smsl", "bus": "x"},
    {"mnem": "LBVS s", "code": "1029smsl", "bus": "x"},
    {"mnem": "LBPL s", "code": "102Asmsl", "bus": "x"},
    {"mnem": "LBMI s", "code": "102Bsmsl", "bus": "x"},
    {"mnem": "LBGE s", "code": "102Csmsl", "bus": "x"},
    {"mnem": "LBLT s", "code": "102Dsmsl", "bus": "x"},
    {"mnem": "LBGT s", "code": "102Esmsl", "bus": "x"},
    {"mnem": "LBLE s", "code": "102Fsmsl", "bus": "x"},
    {"mnem": "SWI2", "code": "103F", "bus": ""},
    {"mnem": "CMPD #w", "code": "1083wmwl", "bus": ""},
    {"mnem": "CMPY #w", "code": "108Cwmwl", "bus": ""},
    {"mnem": "CMPD p", "code": "1093pp", "bus": "r"},
    {"mnem": "CMPY p", "code": "109Cpp", "bus": "r"},
    {"mnem": "LDY p", "code": "109Epp", "bus": "r"},
    {"mnem": "STY p", "code": "109Fpp", "bus": "w"},
    {"mnem": "CMPD y", "code": "10A3yy", "bus": ""},
    {"mnem": "CMPY y", "code": "10ACyy", "bus": ""},
    {"mnem": "LDY y", "code": "10AEyy", "bus": ""},
    {"mnem": "STY y", "code": "10AFyy", "bus": ""},
    {"mnem": "CMPD t", "code": "10B3tmtl", "bus": "r"},
    {"mnem": "CMPY t", "code": "10BCtmtl", "bus": "r"},
    {"mnem": "LDY t", "code": "10BEtmtl", "bus": "r"},
    {"mnem": "STY t", "code": "10BFtmtl", "bus": "w"},
    {"mnem": "LDS #w", "code": "10CEwmwl", "bus": ""},
    {"mnem": "LDS p", "code": "10DEpp", "bus": "r"},
    {"mnem": "STS p", "code": "10DFpp", "bus": "w"},
    {"mnem": "LDS y", "code": "10EEyy", "bus": ""},
    {"mnem": "STS y", "code": "10EFyy", "bus": ""},
    {"mnem": "LDS t", "code": "10FEtmtl", "bus": "r"},
    {"mnem": "STS t", "code": "10FFtmtl", "bus": "w"},
    {"mnem": "SWI3", "code": "113F", "bus": ""},
    {"mnem": "CMPU #w", "code": "1183wmwl", "bus": ""},
    {"mnem": "CMPS #w", "code": "118Cwmwl", "bus": ""},
    {"mnem": "CMPU p", "code": "1193pp", "bus": "r"},
    {"mnem": "CMPS p", "code": "119Cpp", "bus": "r"},
    {"mnem": "CMPU y", "code": "11A3yy", "bus": ""},
    {"mnem": "CMPS y", "code": "11ACyy", "bus": ""},
    {"mnem": "CMPU t", "code": "11B3tmtl", "bus": "r"},
    {"mnem": "CMPS t", "code": "11BCtmtl", "bus": "r"},
    {"mnem": "NOP", "code": "12", "bus": ""},
    {"mnem": "SYNC", "code": "13", "bus": ""},
    {"mnem": "LBRA s", "code": "16smsl", "bus": "x"},
    {"mnem": "LBSR s", "code": "17smsl", "bus": "x"},
    {"mnem": "DAA", "code": "19", "bus": ""},
    {"mnem": "ORCC #b", "code": "1Abb", "bus": ""},
    {"mnem": "ANDCC #b", "code": "1Cbb", "bus": ""},
    {"mnem": "SEX", "code": "1D", "bus": ""},
    {"mnem": "EXG z", "code": "1Ezz", "bus": ""},
    {"mnem": "TFR z", "code": "1Fzz", "bus": ""},
    {"mnem": "BRA r", "code": "20rr", "bus": "x"},
    {"mnem": "BRN r", "code": "21rr", "bus": "x"},
    {"mnem": "BHI r", "code": "22rr", "bus": "x"},
    {"mnem": "BLS r", "code": "23rr", "bus": "x"},
    {"mnem": "BHS r", "code": "24rr", "bus": "x"},
    {"mnem": "BCC r", "code": "24rr", "bus": "x"},
    {"mnem": "BLO r", "code": "25rr", "bus": "x"},
    {"mnem": "BCS r", "code": "25rr", "bus": "x"},
    {"mnem": "BNE r", "code": "26rr", "bus": "x"},
    {"mnem": "BEQ r", "code": "27rr", "bus": "x"},
    {"mnem": "BVC r", "code": "28rr", "bus": "x"},
    {"mnem": "BVS r", "code": "29rr", "bus": "x"},
    {"mnem": "BPL r", "code": "2Arr", "bus": "x"},
    {"mnem": "BMI r", "code": "2Brr", "bus": "x"},
    {"mnem": "BGE r", "code": "2Crr", "bus": "x"},
    {"mnem": "BLT r", "code": "2Drr", "bus": "x"},
    {"mnem": "BGT r", "code": "2Err", "bus": "x"},
    {"mnem": "BLE r", "code": "2Frr", "bus": "x"},
    {"mnem": "LEAX y", "code": "30yy", "bus": ""},
    {"mnem": "LEAY y", "code": "31yy", "bus": ""},
    {"mnem": "LEAS y", "code": "32yy", "bus": ""},
    {"mnem": "LEAU y", "code": "33yy", "bus": ""},
    {"mnem": "PSHS x", "code": "34xx", "bus": ""},
    {"mnem": "PULS q", "code": "35qq", "bus": ""},
    {"mnem": "PSHU u", "code": "36uu", "bus": ""},
    {"mnem": "PULU v", "code": "37vv", "bus": ""},
    {"mnem": "RTS", "code": "39", "bus": ""},
    {"mnem": "ABX", "code": "3A", "bus": ""},
    {"mnem": "RTI", "code": "3B", "bus": ""},
    {"mnem": "CWAI b", "code": "3Cbb", "bus": ""},
    {"mnem": "MUL", "code": "3D", "bus": ""},
    {"mnem": "RESET", "code": "3E", "bus": ""},
    {"mnem": "SWI", "code": "3F", "bus": ""},
    {"mnem": "NEGA", "code": "40", "bus": ""},
    {"mnem": "COMA", "code": "43", "bus": ""},
    {"mnem": "LSRA", "code": "44", "bus": ""},
    {"mnem": "RORA", "code": "46", "bus": ""},
    {"mnem": "ASRA", "code": "47", "bus": ""},
    {"mnem": "ASLA", "code": "48", "bus": ""},
    {"mnem": "LSLA", "code": "48", "bus": ""},
    {"mnem": "ROLA", "code": "49", "bus": ""},
    {"mnem": "DECA", "code": "4A", "bus": ""},
    {"mnem": "INCA", "code": "4C", "bus": ""},
    {"mnem": "TSTA", "code": "4D", "bus": ""},
    {"mnem": "CLRA", "code": "4F", "bus": ""},
    {"mnem": "NEGB", "code": "50", "bus": ""},
    {"mnem": "COMB", "code": "53", "bus": ""},
    {"mnem": "LSRB", "code": "54", "bus": ""},
    {"mnem": "RORB", "code": "56", "bus": ""},
    {"mnem": "ASRB", "code": "57", "bus": ""},
    {"mnem": "ASLB", "code": "58", "bus": ""},
    {"mnem": "LSLB", "code": "58", "bus": ""},
    {"mnem": "ROLB", "code": "59", "bus": ""},
    {"mnem": "DECB", "code": "5A", "bus": ""},
    {"mnem": "INCB", "code": "5C", "bus": ""},
    {"mnem": "TSTB", "code": "5D", "bus": ""},
    {"mnem": "CLRB", "code": "5F", "bus": ""},
    {"mnem": "NEG y", "code": "60yy", "bus": ""},
    {"mnem": "COM y", "code": "63yy", "bus": ""},
    {"mnem": "LSR y", "code": "64yy", "bus": ""},
    {"mnem": "ROR y", "code": "66yy", "bus": ""},
    {"mnem": "ASR y", "code": "67yy", "bus": ""},
    {"mnem": "ASL y", "code": "68yy", "bus": ""},
    {"mnem": "LSL y", "code": "68yy", "bus": ""},
    {"mnem": "ROL y", "code": "69yy", "bus": ""},
    {"mnem": "DEC y", "code": "6Ayy", "bus": ""},
    {"mnem": "INC y", "code": "6Cyy", "bus": ""},
    {"mnem": "TST y", "code": "6Dyy", "bus": ""},
    {"mnem": "JMP y", "code": "6Eyy", "bus": ""},
    {"mnem": "CLR y", "code": "6Fyy", "bus": ""},
    {"mnem": "NEG t", "code": "70tmtl", "bus": "rw"},
    {"mnem": "COM t", "code": "73tmtl", "bus": "rw"},
    {"mnem": "LSR t", "code": "74tmtl", "bus": "rw"},
    {"mnem": "ROR t", "code": "76tmtl", "bus": "rw"},
    {"mnem": "ASR t", "code": "77tmtl", "bus": "rw"},
    {"mnem": "ASL t", "code": "78tmtl", "bus": "rw"},
    {"mnem": "LSL t", "code": "78tmtl", "bus": "rw"},
    {"mnem": "ROL t", "code": "79tmtl", "bus": "rw"},
    {"mnem": "DEC t", "code": "7Atmtl", "bus": "rw"},
    {"mnem": "INC t", "code": "7Ctmtl", "bus": "rw"},
    {"mnem": "TST t", "code": "7Dtmtl", "bus": "r"},
    {"mnem": "JMP t", "code": "7Etmtl", "bus": "x"},
    {"mnem": "CLR t", "code": "7Ftmtl", "bus": "w"},
    {"mnem": "SUBA #b", "code": "80bb", "bus": ""},
    {"mnem": "CMPA #b", "code": "81bb", "bus": ""},
    {"mnem": "SBCA #b", "code": "82bb", "bus": ""},
    {"mnem": "SUBD #w", "code": "83wmwl", "bus": ""},
    {"mnem": "ANDA #b", "code": "84bb", "bus": ""},
    {"mnem": "BITA #b", "code": "85bb", "bus": ""},
    {"mnem": "LDA #b", "code": "86bb", "bus": ""},
    {"mnem": "EORA #b", "code": "88bb", "bus": ""},
    {"mnem": "ADCA #b", "code": "89bb", "bus": ""},
    {"mnem": "ORA #b", "code": "8Abb", "bus": ""},
    {"mnem": "ADDA #b", "code": "8Bbb", "bus": ""},
    {"mnem": "CMPX #w", "code": "8Cwmwl", "bus": ""},
    {"mnem": "BSR r", "code": "8Drr", "bus": "x"},
    {"mnem": "LDX #w", "code": "8Ewmwl", "bus": ""},
    {"mnem": "SUBA p", "code": "90pp", "bus": "r"},
    {"mnem": "CMPA p", "code": "91pp", "bus": "r"},
    {"mnem": "SBCA p", "code": "92pp", "bus": "r"},
    {"mnem": "SUBD p", "code": "93pp", "bus": "r"},
    {"mnem": "ANDA p", "code": "94pp", "bus": "r"},
    {"mnem": "BITA p", "code": "95pp", "bus": "r"},
    {"mnem": "LDA p", "code": "96pp", "bus": "r"},
    {"mnem": "STA p", "code": "97pp", "bus": "w"},
    {"mnem": "EORA p", "code": "98pp", "bus": "r"},
    {"mnem": "ADCA p", "code": "99pp", "bus": "r"},
    {"mnem": "ORA p", "code": "9App", "bus": "r"},
    {"mnem": "ADDA p", "code": "9Bpp", "bus": "r"},
    {"mnem": "CMPX p", "code": "9Cpp", "bus": "r"},
    {"mnem": "JSR p", "code": "9Dpp", "bus": "x"},
    {"mnem": "LDX p", "code": "9Epp", "bus": "r"},
    {"mnem": "STX p", "code": "9Fpp", "bus": "w"},
    {"mnem": "SUBA y", "code": "A0yy", "bus": ""},
    {"mnem": "CMPA y", "code": "A1yy", "bus": ""},
    {"mnem": "SBCA y", "code": "A2yy", "bus": ""},
    {"mnem": "SUBD y", "code": "A3yy", "bus": ""},
    {"mnem": "ANDA y", "code": "A4yy", "bus": ""},
    {"mnem": "BITA y", "code": "A5yy", "bus": ""},
    {"mnem": "LDA y", "code": "A6yy", "bus": ""},
    {"mnem": "STA y", "code": "A7yy", "bus": ""},
    {"mnem": "EORA y", "code": "A8yy", "bus": ""},
    {"mnem": "ADCA y", "code": "A9yy", "bus": ""},
    {"mnem": "ORA y", "code": "AAyy", "bus": ""},
    {"mnem": "ADDA y", "code": "AByy", "bus": ""},
    {"mnem": "CMPX y", "code": "ACyy", "bus": ""},
    {"mnem": "JSR y", "code": "ADyy", "bus": ""},
    {"mnem": "LDX y", "code": "AEyy", "bus": ""},
    {"mnem": "STX y", "code": "AFyy", "bus": ""},
    {"mnem": "SUBA t", "code": "B0tmtl", "bus": "r"},
    {"mnem": "CMPA t", "code": "B1tmtl", "bus": "r"},
    {"mnem": "SBCA t", "code": "B2tmtl", "bus": "r"},
    {"mnem": "SUBD t", "code": "B3tmtl", "bus": "r"},
    {"mnem": "ANDA t", "code": "B4tmtl", "bus": "r"},
    {"mnem": "BITA t", "code": "B5tmtl", "bus": "r"},
    {"mnem": "LDA t", "code": "B6tmtl", "bus": "r"},
    {"mnem": "STA t", "code": "B7tmtl", "bus": "w"},
    {"mnem": "EORA t", "code": "B8tmtl", "bus": "r"},
    {"mnem": "ADCA t", "code": "B9tmtl", "bus": "r"},
    {"mnem": "ORA t", "code": "BAtmtl", "bus": "r"},
    {"mnem": "ADDA t", "code": "BBtmtl", "bus": "r"},
    {"mnem": "CMPX t", "code": "BCtmtl", "bus": "r"},
    {"mnem": "JSR t", "code": "BDtmtl", "bus": "x"},
    {"mnem": "LDX t", "code": "BEtmtl", "bus": "r"},
    {"mnem": "STX t", "code": "BFtmtl", "bus": "w"},
    {"mnem": "SUBB #b", "code": "C0bb", "bus": ""},
    {"mnem": "CMPB #b", "code": "C1bb", "bus": ""},
    {"mnem": "SBCB #b", "code": "C2bb", "bus": ""},
    {"mnem": "ADDD #w", "code": "C3wmwl", "bus": ""},
    {"mnem": "ANDB #b", "code": "C4bb", "bus": ""},
    {"mnem": "BITB #b", "code": "C5bb", "bus": ""},
    {"mnem": "LDB #b", "code": "C6bb", "bus": ""},
    {"mnem": "EORB #b", "code": "C8bb", "bus": ""},
    {"mnem": "ADCB #b", "code": "C9bb", "bus": ""},
    {"mnem": "ORB #b", "code": "CAbb", "bus": ""},
    {"mnem": "ADDB #b", "code": "CBbb", "bus": ""},
    {"mnem": "LDD #w", "code": "CCwmwl", "bus": ""},
    {"mnem": "LDU #w", "code": "CEwmwl", "bus": ""},
    {"mnem": "SUBB p", "code": "D0pp", "bus": "r"},
    {"mnem": "CMPB p", "code": "D1pp", "bus": "r"},
    {"mnem": "SBCB p", "code": "D2pp", "bus": "r"},
    {"mnem": "ADDD p", "code": "D3pp", "bus": "r"},
    {"mnem": "ANDB p", "code": "D4pp", "bus": "r"},
    {"mnem": "BITB p", "code": "D5pp", "bus": "r"},
    {"mnem": "LDB p", "code": "D6pp", "bus": "r"},
    {"mnem": "STB p", "code": "D7pp", "bus": "w"},
    {"mnem": "EORB p", "code": "D8pp", "bus": ""},
    {"mnem": "ADCB p", "code": "D9pp", "bus": "r"},
    {"mnem": "ORB p", "code": "DApp", "bus": "r"},
    {"mnem": "ADDB p", "code": "DBpp", "bus": "r"},
    {"mnem": "LDD p", "code": "DCpp", "bus": "r"},
    {"mnem": "STD p", "code": "DDpp", "bus": "w"},
    {"mnem": "LDU p", "code": "DEpp", "bus": "r"},
    {"mnem": "STU p", "code": "DFpp", "bus": "w"},
    {"mnem": "SUBB y", "code": "E0yy", "bus": ""},
    {"mnem": "CMPB y", "code": "E1yy", "bus": ""},
    {"mnem": "SBCB y", "code": "E2yy", "bus": ""},
    {"mnem": "ADDD y", "code": "E3yy", "bus": ""},
    {"mnem": "ANDB y", "code": "E4yy", "bus": ""},
    {"mnem": "BITB y", "code": "E5yy", "bus": ""},
    {"mnem": "LDB y", "code": "E6yy", "bus": ""},
    {"mnem": "STB y", "code": "E7yy", "bus": ""},
    {"mnem": "EORB y", "code": "E8yy", "bus": ""},
    {"mnem": "ADCB y", "code": "E9yy", "bus": ""},
    {"mnem": "ORB y", "code": "EAyy", "bus": ""},
    {"mnem": "ADDB y", "code": "EByy", "bus": ""},
    {"mnem": "LDD y", "code": "ECyy", "bus": ""},
    {"mnem": "STD y", "code": "EDyy", "bus": ""},
    {"mnem": "LDU y", "code": "EEyy", "bus": ""},
    {"mnem": "STU y", "code": "EFyy", "bus": ""},
    {"mnem": "SUBB t", "code": "F0tmtl", "bus": "r"},
    {"mnem": "CMPB t", "code": "F1tmtl", "bus": "r"},
    {"mnem": "SBCB t", "code": "F2tmtl", "bus": "r"},
    {"mnem": "ADDD t", "code": "F3tmtl", "bus": "r"},
    {"mnem": "ANDB t", "code": "F4tmtl", "bus": "r"},
    {"mnem": "BITB t", "code": "F5tmtl", "bus": "r"},
    {"mnem": "LDB t", "code": "F6tmtl", "bus": "r"},
    {"mnem": "STB t", "code": "F7tmtl", "bus": "w"},
    {"mnem": "EORB t", "code": "F8tmtl", "bus": "r"},
    {"mnem": "ADCB t", "code": "F9tmtl", "bus": "r"},
    {"mnem": "ORB t", "code": "FAtmtl", "bus": "r"},
    {"mnem": "ADDB t", "code": "FBtmtl", "bus": "r"},
    {"mnem": "LDD t", "code": "FCtmtl", "bus": "r"},
    {"mnem": "STD t", "code": "FDtmtl", "bus": "w"},
    {"mnem": "LDU t", "code": "FEtmtl", "bus": "r"},
    {"mnem": "STU t", "code": "FFtmtl", "bus": "w"},
]

POSTS = [
    {"post": "0,X", "code": "00"},
    {"post": "1,X", "code": "01"},
    {"post": "2,X", "code": "02"},
    {"post": "3,X", "code": "03"},
    {"post": "4,X", "code": "04"},
    {"post": "5,X", "code": "05"},
    {"post": "6,X", "code": "06"},
    {"post": "7,X", "code": "07"},
    {"post": "8,X", "code": "08"},
    {"post": "9,X", "code": "09"},
    {"post": "10,X", "code": "0A"},
    {"post": "11,X", "code": "0B"},
    {"post": "12,X", "code": "0C"},
    {"post": "13,X", "code": "0D"},
    {"post": "14,X", "code": "0E"},
    {"post": "15,X", "code": "0F"},
    {"post": "-16,X", "code": "10"},
    {"post": "-15,X", "code": "11"},
    {"post": "-14,X", "code": "12"},
    {"post": "-13,X", "code": "13"},
    {"post": "-12,X", "code": "14"},
    {"post": "-11,X", "code": "15"},
    {"post": "-10,X", "code": "16"},
    {"post": "-9,X", "code": "17"},
    {"post": "-8,X", "code": "18"},
    {"post": "-7,X", "code": "19"},
    {"post": "-6,X", "code": "1A"},
    {"post": "-5,X", "code": "1B"},
    {"post": "-4,X", "code": "1C"},
    {"post": "-3,X", "code": "1D"},
    {"post": "-2,X", "code": "1E"},
    {"post": "-1,X", "code": "1F"},
    {"post": "0,Y", "code": "20"},
    {"post": "1,Y", "code": "21"},
    {"post": "2,Y", "code": "22"},
    {"post": "3,Y", "code": "23"},
    {"post": "4,Y", "code": "24"},
    {"post": "5,Y", "code": "25"},
    {"post": "6,Y", "code": "26"},
    {"post": "7,Y", "code": "27"},
    {"post": "8,Y", "code": "28"},
    {"post": "9,Y", "code": "29"},
    {"post": "10,Y", "code": "2A"},
    {"post": "11,Y", "code": "2B"},
    {"post": "12,Y", "code": "2C"},
    {"post": "13,Y", "code": "2D"},
    {"post": "14,Y", "code": "2E"},
    {"post": "15,Y", "code": "2F"},
    {"post": "-16,Y", "code": "30"},
    {"post": "-15,Y", "code": "31"},
    {"post": "-14,Y", "code": "32"},
    {"post": "-13,Y", "code": "33"},
    {"post": "-12,Y", "code": "34"},
    {"post": "-11,Y", "code": "35"},
    {"post": "-10,Y", "code": "36"},
    {"post": "-9,Y", "code": "37"},
    {"post": "-8,Y", "code": "38"},
    {"post": "-7,Y", "code": "39"},
    {"post": "-6,Y", "code": "3A"},
    {"post": "-5,Y", "code": "3B"},
    {"post": "-4,Y", "code": "3C"},
    {"post": "-3,Y", "code": "3D"},
    {"post": "-2,Y", "code": "3E"},
    {"post": "-1,Y", "code": "3F"},
    {"post": "0,U", "code": "40"},
    {"post": "1,U", "code": "41"},
    {"post": "2,U", "code": "42"},
    {"post": "3,U", "code": "43"},
    {"post": "4,U", "code": "44"},
    {"post": "5,U", "code": "45"},
    {"post": "6,U", "code": "46"},
    {"post": "7,U", "code": "47"},
    {"post": "8,U", "code": "48"},
    {"post": "9,U", "code": "49"},
    {"post": "10,U", "code": "4A"},
    {"post": "11,U", "code": "4B"},
    {"post": "12,U", "code": "4C"},
    {"post": "13,U", "code": "4D"},
    {"post": "14,U", "code": "4E"},
    {"post": "15,U", "code": "4F"},
    {"post": "-16,U", "code": "50"},
    {"post": "-15,U", "code": "51"},
    {"post": "-14,U", "code": "52"},
    {"post": "-13,U", "code": "53"},
    {"post": "-12,U", "code": "54"},
    {"post": "-11,U", "code": "55"},
    {"post": "-10,U", "code": "56"},
    {"post": "-9,U", "code": "57"},
    {"post": "-8,U", "code": "58"},
    {"post": "-7,U", "code": "59"},
    {"post": "-6,U", "code": "5A"},
    {"post": "-5,U", "code": "5B"},
    {"post": "-4,U", "code": "5C"},
    {"post": "-3,U", "code": "5D"},
    {"post": "-2,U", "code": "5E"},
    {"post": "-1,U", "code": "5F"},
    {"post": "0,S", "code": "60"},
    {"post": "1,S", "code": "61"},
    {"post": "2,S", "code": "62"},
    {"post": "3,S", "code": "63"},
    {"post": "4,S", "code": "64"},
    {"post": "5,S", "code": "65"},
    {"post": "6,S", "code": "66"},
    {"post": "7,S", "code": "67"},
    {"post": "8,S", "code": "68"},
    {"post": "9,S", "code": "69"},
    {"post": "10,S", "code": "6A"},
    {"post": "11,S", "code": "6B"},
    {"post": "12,S", "code": "6C"},
    {"post": "13,S", "code": "6D"},
    {"post": "14,S", "code": "6E"},
    {"post": "15,S", "code": "6F"},
    {"post": "-16,S", "code": "70"},
    {"post": "-15,S", "code": "71"},
    {"post": "-14,S", "code": "72"},
    {"post": "-13,S", "code": "73"},
    {"post": "-12,S", "code": "74"},
    {"post": "-11,S", "code": "75"},
    {"post": "-10,S", "code": "76"},
    {"post": "-9,S", "code": "77"},
    {"post": "-8,S", "code": "78"},
    {"post": "-7,S", "code": "79"},
    {"post": "-6,S", "code": "7A"},
    {"post": "-5,S", "code": "7B"},
    {"post": "-4,S", "code": "7C"},
    {"post": "-3,S", "code": "7D"},
    {"post": "-2,S", "code": "7E"},
    {"post": "-1,S", "code": "7F"},
    {"post": ",X+", "code": "80"},
    {"post": ",X++", "code": "81"},
    {"post": ",-X", "code": "82"},
    {"post": ",--X", "code": "83"},
    {"post": ",X", "code": "84"},
    {"post": "B,X", "code": "85"},
    {"post": "A,X", "code": "86"},
    {"post": "i,X", "code": "88ii"},
    {"post": "k,X", "code": "89kmkl"},
    {"post": "D,X", "code": "8B"},
    {"post": "i,PC", "code": "8Cii"},
    {"post": "k,PC", "code": "8Dkmkl"},
    {"post": "[,X++]", "code": "91"},
    {"post": "[,--X]", "code": "93"},
    {"post": "[,X]", "code": "94"},
    {"post": "[B,X]", "code": "95"},
    {"post": "[A,X]", "code": "96"},
    {"post": "[i,X]", "code": "98ii"},
    {"post": "[k,X]", "code": "99kmkl"},
    {"post": "[D,X]", "code": "9B"},
    {"post": "[i,PC]", "code": "9Cii"},
    {"post": "[k,PC]", "code": "9Dkmkl"},
    {"post": "[t]", "code": "9Ftmtl"},
    {"post": ",Y+", "code": "A0"},
    {"post": ",Y++", "code": "A1"},
    {"post": ",-Y", "code": "A2"},
    {"post": ",--Y", "code": "A3"},
    {"post": ",Y", "code": "A4"},
    {"post": "B,Y", "code": "A5"},
    {"post": "A,Y", "code": "A6"},
    {"post": "i,Y", "code": "A8ii"},
    {"post": "k,Y", "code": "A9kmkl"},
    {"post": "D,Y", "code": "AB"},
    {"post": "i,PC", "code": "ACii"},
    {"post": "k,PC", "code": "ADkmkl"},
    {"post": "[,Y++]", "code": "B1"},
    {"post": "[,--Y]", "code": "B3"},
    {"post": "[,Y]", "code": "B4"},
    {"post": "[B,Y]", "code": "B5"},
    {"post": "[A,Y]", "code": "B6"},
    {"post": "[i,Y]", "code": "B8ii"},
    {"post": "[k,Y]", "code": "B9kmkl"},
    {"post": "[D,Y]", "code": "BB"},
    {"post": "[i,PC]", "code": "BCii"},
    {"post": "[k,PC]", "code": "BDkmkl"},
    {"post": "[t]", "code": "BFtmtl"},
    {"post": ",U+", "code": "C0"},
    {"post": ",U++", "code": "C1"},
    {"post": ",-U", "code": "C2"},
    {"post": ",--U", "code": "C3"},
    {"post": ",U", "code": "C4"},
    {"post": "B,U", "code": "C5"},
    {"post": "A,U", "code": "C6"},
    {"post": "i,U", "code": "C8ii"},
    {"post": "k,U", "code": "C9kmkl"},
    {"post": "D,U", "code": "CB"},
    {"post": "i,PC", "code": "CCii"},
    {"post": "k,PC", "code": "CDkmkl"},
    {"post": "[,U++]", "code": "D1"},
    {"post": "[,--U]", "code": "D3"},
    {"post": "[,U]", "code": "D4"},
    {"post": "[B,U]", "code": "D5"},
    {"post": "[A,U]", "code": "D6"},
    {"post": "[i,U]", "code": "D8ii"},
    {"post": "[k,U]", "code": "D9kmkl"},
    {"post": "[D,U]", "code": "DB"},
    {"post": "[i,PC]", "code": "DCii"},
    {"post": "[k,PC]", "code": "DDkmkl"},
    {"post": "[t]", "code": "DFtmtl"},
    {"post": ",S+", "code": "E0"},
    {"post": ",S++", "code": "E1"},
    {"post": ",-S", "code": "E2"},
    {"post": ",--S", "code": "E3"},
    {"post": ",S", "code": "E4"},
    {"post": "B,S", "code": "E5"},
    {"post": "A,S", "code": "E6"},
    {"post": "i,S", "code": "E8ii"},
    {"post": "k,S", "code": "E9kmkl"},
    {"post": "i,X", "code": "EAii"},
    {"post": "D,S", "code": "EB"},
    {"post": "i,PC", "code": "ECii"},
    {"post": "k,PC", "code": "EDkmkl"},
    {"post": "[,S++]", "code": "F1"},
    {"post": "[,--S]", "code": "F3"},
    {"post": "[,S]", "code": "F4"},
    {"post": "[B,S]", "code": "F5"},
    {"post": "[A,S]", "code": "F6"},
    {"post": "[i,S]", "code": "F8ii"},
    {"post": "[k,S]", "code": "F9kmkl"},
    {"post": "[D,S]", "code": "FB"},
    {"post": "[i,PC]", "code": "FCii"},
    {"post": "[k,PC]", "code": "FDkmkl"},
    {"post": "[t]", "code": "FFtmtl"}
]

# TODO: LDA $FF00,PC ; PC relative


class CPU_6809(cpu.base_cpu.CPU):

    def __init__(self):

        expanded_opcodes = []

        # Expand the "post" mnemonics
        for entry in OPCODES:
            if 'y' in entry['mnem']:
                for post in POSTS:
                    new_mnem = entry['mnem'].replace('y', post['post'])
                    new_code = entry['code'].replace('yy', post['code'])
                    new_entry = {'mnem': new_mnem,
                                 # 'code': new_code, 'bus': entry['bus']}
                                 'code': new_code, 'bus': ''}
                    expanded_opcodes.append(new_entry)
            else:
                expanded_opcodes.append(entry)

        super().__init__(expanded_opcodes)
