import cpu.cpu_common

OPCODES = [
    {"mnem": "BRK", "code": "00", "bus": ""},
    {"mnem": "ORA (p,X)", "code": "01pp", "bus": ""},
    {"mnem": "ORA p", "code": "05pp", "bus": "r"},
    {"mnem": "ASL p", "code": "06pp", "bus": "rw"},
    {"mnem": "PHP", "code": "08", "bus": ""},
    {"mnem": "ORA #b", "code": "09bb", "bus": ""},
    {"mnem": "ASL A", "code": "0A", "bus": ""},
    {"mnem": "ORA t", "code": "0Dtltm", "bus": "r"},
    {"mnem": "ASL t", "code": "0Etltm", "bus": "rw"},
    {"mnem": "BPL r", "code": "10rr", "bus": "x"},
    {"mnem": "ORA (p),Y", "code": "11pp", "bus": ""},
    {"mnem": "ORA p,X", "code": "15pp", "bus": ""},
    {"mnem": "ASL p,X", "code": "16pp", "bus": ""},
    {"mnem": "CLC", "code": "18", "bus": ""},
    {"mnem": "ORA t,Y", "code": "19tltm", "bus": ""},
    {"mnem": "ORA t,X", "code": "1Dtltm", "bus": ""},
    {"mnem": "ASL t,X", "code": "1Etltm", "bus": ""},
    {"mnem": "JSR t", "code": "20tltm", "bus": "x"},
    {"mnem": "AND (p,X)", "code": "21pp", "bus": ""},
    {"mnem": "BIT p", "code": "24pp", "bus": "r"},
    {"mnem": "AND p", "code": "25pp", "bus": "r"},
    {"mnem": "ROL p", "code": "26pp", "bus": "rw"},
    {"mnem": "PLP", "code": "28", "bus": "r"},
    {"mnem": "AND #b", "code": "29bb", "bus": ""},
    {"mnem": "ROL A", "code": "2A", "bus": ""},
    {"mnem": "BIT t", "code": "2Ctltm", "bus": "r"},
    {"mnem": "AND t", "code": "2Dtltm", "bus": "r"},
    {"mnem": "ROL t", "code": "2Etltm", "bus": "rw"},
    {"mnem": "BMI r", "code": "30rr", "bus": "x"},
    {"mnem": "AND (p),Y", "code": "31pp", "bus": ""},
    {"mnem": "AND p,X", "code": "35pp", "bus": ""},
    {"mnem": "ROL p,X", "code": "36pp", "bus": ""},
    {"mnem": "SEC", "code": "38", "bus": ""},
    {"mnem": "AND t,Y", "code": "39tltm", "bus": ""},
    {"mnem": "AND t,X", "code": "3Dtltm", "bus": ""},
    {"mnem": "ROL t,X", "code": "3Etltm", "bus": ""},
    {"mnem": "RTI", "code": "40", "bus": ""},
    {"mnem": "EOR (p,X)", "code": "41pp", "bus": ""},
    {"mnem": "EOR p", "code": "45pp", "bus": "r"},
    {"mnem": "LSR p", "code": "46pp", "bus": "rw"},
    {"mnem": "PHA", "code": "48", "bus": ""},
    {"mnem": "EOR #b", "code": "49bb", "bus": ""},
    {"mnem": "LSR A", "code": "4A", "bus": ""},
    {"mnem": "JMP t", "code": "4Ctltm", "bus": "x"},
    {"mnem": "EOR t", "code": "4Dtltm", "bus": "r"},
    {"mnem": "LSR t", "code": "4Etltm", "bus": "rw"},
    {"mnem": "BVC r", "code": "50rr", "bus": "x"},
    {"mnem": "EOR (p),Y", "code": "51pp", "bus": ""},
    {"mnem": "EOR p,X", "code": "55pp", "bus": ""},
    {"mnem": "LSR p,X", "code": "56pp", "bus": ""},
    {"mnem": "CLI", "code": "58", "bus": ""},
    {"mnem": "EOR t,Y", "code": "59tltm", "bus": ""},
    {"mnem": "EOR t,X", "code": "5Dtltm", "bus": ""},
    {"mnem": "LSR t,X", "code": "5Etltm", "bus": ""},
    {"mnem": "RTS", "code": "60", "bus": ""},
    {"mnem": "ADC (p,X)", "code": "61pp", "bus": ""},
    {"mnem": "ADC p", "code": "65pp", "bus": "r"},
    {"mnem": "ROR p", "code": "66pp", "bus": "rw"},
    {"mnem": "PLA", "code": "68", "bus": "r"},
    {"mnem": "ADC #b", "code": "69bb", "bus": ""},
    {"mnem": "ROR A", "code": "6A", "bus": ""},
    {"mnem": "JMP (t)", "code": "6Ctltm", "bus": "x"},
    {"mnem": "ADC t", "code": "6Dtltm", "bus": "r"},
    {"mnem": "ROR t", "code": "6Etltm", "bus": "r"},
    {"mnem": "BVS r", "code": "70rr", "bus": "x"},
    {"mnem": "ADC (p),Y", "code": "71pp", "bus": ""},
    {"mnem": "ADC p,X", "code": "75pp", "bus": ""},
    {"mnem": "ROR p,X", "code": "76pp", "bus": ""},
    {"mnem": "SEI", "code": "78", "bus": ""},
    {"mnem": "ADC t,Y", "code": "79tltm", "bus": ""},
    {"mnem": "ADC t,X", "code": "7Dtltm", "bus": ""},
    {"mnem": "ROR t,X", "code": "7Etltm", "bus": ""},
    {"mnem": "STA (p,X)", "code": "81pp", "bus": ""},
    {"mnem": "STY p", "code": "84pp", "bus": "w"},
    {"mnem": "STA p", "code": "85pp", "bus": "w"},
    {"mnem": "STX p", "code": "86pp", "bus": "w"},
    {"mnem": "DEY", "code": "88", "bus": ""},
    {"mnem": "TXA", "code": "8A", "bus": ""},
    {"mnem": "STY t", "code": "8Ctltm", "bus": "w"},
    {"mnem": "STA t", "code": "8Dtltm", "bus": "w"},
    {"mnem": "STX t", "code": "8Etltm", "bus": "w"},
    {"mnem": "BCC r", "code": "90rr", "bus": "x"},
    {"mnem": "STA (p),Y", "code": "91pp", "bus": ""},
    {"mnem": "STY p,X", "code": "94pp", "bus": ""},
    {"mnem": "STA p,X", "code": "95pp", "bus": ""},
    {"mnem": "STX p,Y", "code": "96pp", "bus": ""},
    {"mnem": "TYA", "code": "98", "bus": ""},
    {"mnem": "STA t,Y", "code": "99tltm", "bus": ""},
    {"mnem": "TXS", "code": "9A", "bus": ""},
    {"mnem": "STA t,X", "code": "9Dtltm", "bus": ""},
    {"mnem": "LDY #b", "code": "A0bb", "bus": ""},
    {"mnem": "LDA (p,X)", "code": "A1pp", "bus": ""},
    {"mnem": "LDX #b", "code": "A2bb", "bus": ""},
    {"mnem": "LDY p", "code": "A4pp", "bus": "r"},
    {"mnem": "LDA p", "code": "A5pp", "bus": "r"},
    {"mnem": "LDX p", "code": "A6pp", "bus": "r"},
    {"mnem": "TAY", "code": "A8", "bus": ""},
    {"mnem": "LDA #b", "code": "A9bb", "bus": ""},
    {"mnem": "TAX", "code": "AA", "bus": ""},
    {"mnem": "LDY t", "code": "ACtltm", "bus": "r"},
    {"mnem": "LDA t", "code": "ADtltm", "bus": "r"},
    {"mnem": "LDX t", "code": "AEtltm", "bus": "r"},
    {"mnem": "BCS r", "code": "B0rr", "bus": "x"},
    {"mnem": "LDA (p),Y", "code": "B1pp", "bus": ""},
    {"mnem": "LDY p,X", "code": "B4pp", "bus": ""},
    {"mnem": "LDA p,X", "code": "B5pp", "bus": ""},
    {"mnem": "LDX p,Y", "code": "B6pp", "bus": ""},
    {"mnem": "CLV", "code": "B8", "bus": ""},
    {"mnem": "LDA t,Y", "code": "B9tltm", "bus": ""},
    {"mnem": "TSX", "code": "BA", "bus": ""},
    {"mnem": "LDY t,X", "code": "BCtltm", "bus": ""},
    {"mnem": "LDA t,X", "code": "BDtltm", "bus": ""},
    {"mnem": "LDX t,Y", "code": "BEtltm", "bus": ""},
    {"mnem": "CPY #b", "code": "C0bb", "bus": ""},
    {"mnem": "CMP (p,X)", "code": "C1pp", "bus": ""},
    {"mnem": "CPY p", "code": "C4pp", "bus": "r"},
    {"mnem": "CMP p", "code": "C5pp", "bus": "r"},
    {"mnem": "DEC p", "code": "C6pp", "bus": "rw"},
    {"mnem": "INY", "code": "C8", "bus": ""},
    {"mnem": "CMP #b", "code": "C9bb", "bus": ""},
    {"mnem": "DEX", "code": "CA", "bus": ""},
    {"mnem": "CPY t", "code": "CCtltm", "bus": "r"},
    {"mnem": "CMP t", "code": "CDtltm", "bus": "r"},
    {"mnem": "DEC t", "code": "CEtltm", "bus": "rw"},
    {"mnem": "BNE r", "code": "D0rr", "bus": "x"},
    {"mnem": "CMP (p),Y", "code": "D1pp", "bus": ""},
    {"mnem": "CMP p,X", "code": "D5pp", "bus": ""},
    {"mnem": "DEC p,X", "code": "D6pp", "bus": ""},
    {"mnem": "CLD", "code": "D8", "bus": ""},
    {"mnem": "CMP t,Y", "code": "D9tltm", "bus": ""},
    {"mnem": "CMP t,X", "code": "DDtltm", "bus": ""},
    {"mnem": "DEC t,X", "code": "DEtltm", "bus": ""},
    {"mnem": "CPX #b", "code": "E0bb", "bus": ""},
    {"mnem": "SBC (p,X)", "code": "E1pp", "bus": ""},
    {"mnem": "CPX p", "code": "E4pp", "bus": "r"},
    {"mnem": "SBC p", "code": "E5pp", "bus": "r"},
    {"mnem": "INC p", "code": "E6pp", "bus": "rw"},
    {"mnem": "INX", "code": "E8", "bus": ""},
    {"mnem": "SBC #b", "code": "E9bb", "bus": ""},
    {"mnem": "NOP", "code": "EA", "bus": ""},
    {"mnem": "CPX t", "code": "ECtltm", "bus": "r"},
    {"mnem": "SBC t", "code": "EDtltm", "bus": "r"},
    {"mnem": "INC t", "code": "EEtltm", "bus": "rw"},
    {"mnem": "BEQ r", "code": "F0rr", "bus": "x"},
    {"mnem": "SBC (p),Y", "code": "F1pp", "bus": ""},
    {"mnem": "SBC p,X", "code": "F5pp", "bus": ""},
    {"mnem": "INC p,X", "code": "F6pp", "bus": ""},
    {"mnem": "SED", "code": "F8", "bus": ""},
    {"mnem": "SBC t,Y", "code": "F9tltm", "bus": ""},
    {"mnem": "SBC t,X", "code": "FDtltm", "bus": ""},
    {"mnem": "INC t,X", "code": "FEtltm", "bus": ""}
]


class CPU_6502(cpu.cpu_common.CPU):

    def __init__(self):
        super().__init__(OPCODES)
