SECTIONS = {
    0x01: 'ADJECTIVES',
    0x02: 'SHORT_NAME',
    0x03: 'DESCRIPTION',
    0x04: 'COMMANDS',
    0x06: 'IF_SECOND_NOUN',
    0x07: 'IF_FIRST_NOUN',
    0x08: 'EVERY_TURN',
    0x09: 'HIT_POINTS',
    0x0A: 'UPON_DEATH',
    0x0B: 'IF_GIVEN_COMMAND',
    0x0C: 'WEIGHT',   
}

ROOMS = {

    1: {          
        0x00: 'nowhere', 
        0x01: 'PLAYER', 
        0x80: 'HIGHWAY_WEST',
        0x81: 'WEST_OF_STATION1',
        0x82: 'FRONT_OF_STATION',
        0x83: 'GAS_STATION',
        0x84: 'WEST_OF_STATION2',
        0x85: 'SOUTHWEST_OF_STATION',
        0x86: 'JUNKYARD',
        0x87: 'SOUTHEAST_OF_STATION',
        0x88: 'EAST_OF_STATION',
        0x89: 'CITY_LIMIT',
        0x8C: 'SOUTHWEST_OF_SHERIFF',
        0xAD: 'NORTH_OF_HIGHWAY1',
        0xAE: 'NORTH_OF_HIGHWAY2',
        0xAF: 'NORTH_OF_HIGHWAY3',
        0xB0: 'DESERT_SOUTH1',
        0xDA: 'RESTROOM',
    },
    2: {
        0x8A: 'WEST_OF_TOWN',
        0x8B: 'WEST_OF_SHERIFF',
        0x8D: 'MAIN_STREET_WEST',
        0x8E: 'SHERIFFS_OFFICE',
        0x8F: 'SOUTH_OF_SHERIFF',
        0x92: 'SOUTH_OF_WEST_ALLEY',
        0x9F: 'NORTHWEST_OF_SALOON',
        0xA0: 'WEST_SIDE_OF_SALOON',
        0xA1: 'NORTH_OF_SALOON',
        0xA2: 'SALOON',
        0xA3: 'NORTH_OF_WEST_ALLEY',
        0xA4: 'WEST_ALLEY_NORTH',
        0xB6: 'DESERT_NORTH1',
        0xB7: 'DESERT_PATH',
        0xDB: 'STORM_SHELTER',
    },
    3: {
        0x90: 'WEST_ALLEY_INTERSECTION',
        0x91: 'WEST_ALLEY_SOUTH',
        0x93: 'TOWN_CENTER',
        0x94: 'SLIMS_GROCERY',
        0x95: 'SOUTH_OF_SLIMS',
        0x96: 'EAST_ALLEY_INTERSECTION',
        0x97: 'EAST_ALLEY_SOUTH',
        0x98: 'SOUTH_OF_EAST_ALLEY',
        0xA5: 'NORTH_OF_BOBS',
        0xA6: 'HARDWARE_SOUTH',
        0xA7: 'NORTH_OF_EAST_ALLEY',
        0xA8: 'EAST_ALLEY_NORTH',
        0xB1: 'DESERT_SOUTH2',
        0xB3: 'DESERT1',
        0xB8: 'DESERT_NORTH2',
        0xDC: 'HARDWARE_NORTH',
    },
    4: {
        0x99: 'MAIN_STREET_EAST',
        0x9A: 'BANK',
        0x9B: 'SOUTH_OF_BANK',
        0x9C: 'EAST_OF_TOWN',
        0x9D: 'EAST_OF_BANK',
        0x9E: 'SOUTHEAST_OF_BANK',
        0xA9: 'NORTH_OF_HOTEL',
        0xAA: 'HOTEL_LOBBY',
        0xAB: 'NORTHEAST_OF_HOTEL',
        0xAC: 'EAST_OF_HOTEL',
        0xB2: 'DESERT_SOUTH3',
        0xB4: 'HIGHWAY_EAST',
        0xB5: 'SOUTH_OF_HIGHWAY',
        0xB9: 'NORTH_OF_HIGHWAY4',
        0xDD: 'HALLWAY',
        0xDE: 'NORTH_ROOM',
        0xDF: 'SOUTH_ROOM',
    },
    5: {
        0x98: 'DESERT2',
        0x99: 'DESERT_CANYON1',
        0x9A: 'DESERT_CANYON2',
        0x9B: 'NARROW_PATH',
        0x9C: 'CANYON_FLOOR',
        0x9D: 'UFO_CRATER',
        0x9E: 'DESERT_STRANGE_FOOTPRINTS1',
        0x9F: 'DESERT_CANYON3',
        0xA0: 'DESERT_ERRATIC_FOOTPRINTS',
        0xA1: 'DESERT_WEAVING_FOOTPRINTS',
        0xA2: 'STRANGE_FOOTPRINTS2',
        0xA3: 'DESERT3',
        0xA4: 'DESERT4',
        0xA5: 'DESERT5',
        0xA6: 'DESERT6',
        0xBA: 'DESERT7',
        0xBB: 'DESERT8',
        0xBC: 'DESERT9',
        0xBD: 'DESERT_FOOTPRINTS_LEAD',
        0xBE: 'DESERT_STRANGE_FOOTPRINTS3',
        0xBF: 'DESERT_WEARY_FOOTPRINTS',
        0xC0: 'DESERT_STAGGERING_FOOTPRINTS',
        0xC1: 'DESERT_CRAWL_MARKS',
        0xC2: 'DESERT10',
        0xC3: 'DESERT11',
        0xC4: 'DESERT12',
        0xD3: 'DESERT13',
        0xD4: 'DESERT_TRAIL1',
        0xD5: 'DESERT14',
        0xD6: 'DESERT15',
        0xD7: 'DESERT_TRAIL2',
        0xD8: 'DESERT_TRAIL3',
        0xD9: 'DESERT16',
        0xDA: 'DESERT17',
        0xDB: 'DESERT18',
        0xDC: 'DESERT19',
        0xDD: 'DESERT_HIGHWAY_CURVES',
        0xDE: 'DESERT_HIGHWAY_LEADS',
        0xDF: 'DESERT20',
        0xE0: 'DESERT21',
        0xE1: 'DESERT22',
        0xE2: 'DESERT23',
        0xE8: 'DESERT24',
        0xE9: 'DESERT_TRAIL4',
        0xEA: 'DESERT25',
        0xEB: 'DESERT_TRAIL5',
        0xEC: 'DESERT_TRAIL6',
        0xED: 'DESERT26',
        0xEE: 'DESERT_EMPTY_HIGHWAY1',
        0xEF: 'DESERT_EMPTY_HIGHWAY2',
        0xF0: 'EMPTY_HIGHWAY_DESERT',
        0xF1: 'DESERT_SMALL_TRAIL1',
        0xF2: 'DESERT_TWISTY_TRAIL',
        0xF3: 'DESERT_TRAIL_FORKS',
        0xF4: 'DESERT_TRAIL7',
        0xF5: 'DESERT27',
        0xF6: 'DESERT_SMALL_TRAIL2',
        0xF7: 'DESERT28',
        0xF8: 'DESERT29',
        0xF9: 'DESERT30',
        0xFA: 'DESERT31',
    },        
    6: {
        0x81: 'DESERT32',
        0x82: 'DESERT33',
        0x83: 'DESERT34',
        0x84: 'DESERT35',
        0x85: 'DESERT36',
        0x86: 'DESERT37',
        0x87: 'DESERT38',
        0x88: 'DESERT39',
        0x89: 'DESERT40',
        0x8A: 'DESERT41',
        0x8B: 'DESERT42',
        0x8C: 'DESERT43',
        0x8D: 'DESERT44',
        0x8E: 'DESERT45',
        0x8F: 'DESERT_EMPTY_HIGHWAY3',
        0x90: 'DESERT46',
        0x91: 'DESERT47',
        0x92: 'DESERT48',
        0x93: 'DESERT_CANYON_LAKE1',
        0x94: 'DESERT_LAKE1',
        0x95: 'DESERT_CANYON_LAKE2',
        0x96: 'DESERT_CANYON_LAKE3',
        0x97: 'DESERT_CANYON4',
        0xA7: 'DESERT_EMPTY_HIGHWAY4',
        0xA8: 'DESERT49',
        0xA9: 'DESERT50',
        0xAA: 'DESERT51',
        0xAB: 'DESERT52',
        0xAC: 'DESERT53',
        0xAD: 'DESERT54',
        0xAE: 'DESERT55',
        0xAF: 'DESERT56',
        0xB0: 'DESERT_SMALL_OASIS',
        0xB1: 'DESERT57',
        0xB2: 'DESERT58',
        0xB3: 'DESERT59',
        0xB4: 'DESERT_EMPTY_HIGHWAY5',
        0xB5: 'DESERT60',
        0xB6: 'DESERT61',
        0xB7: 'DESERT_LAKE2',
        0xB8: 'DESERT_LAKE3',
        0xB9: 'DESERT_LAKE4',
        0xC5: 'DESERT_EMPTY_HIGHWAY6',
        0xC6: 'DESERT_HIGHWAY_TURNS',
        0xC7: 'DESERT62',
        0xC8: 'DESERT63',
        0xC9: 'DESERT64',
        0xCA: 'DESERT65',
        0xCB: 'DESERT66',
        0xCC: 'DESERT67',
        0xCD: 'DESERT68',
        0xCE: 'DESERT_EMPTY_HIGHWAY7',
        0xCF: 'DESERT69',
        0xD0: 'DESERT70',
        0xD1: 'DESERT71',
        0xD2: 'DESERT72',
        0xE3: 'DESERT73',
        0xE4: 'DESERT_EMPTY_HIGHWAY8',
        0xE5: 'DESERT74',
        0xE6: 'DESERT75',
        0xE7: 'DESERT76',
        0xF7: 'DESERT77',
        0xF8: 'DESERT78',
        0xF9: 'DESERT79',
        0xFA: 'DESERT80',
    },
    7: {
        0x80: 'EXIT1',
        0x82: 'LOUNGE',
        0x83: 'AIRLOCK1',
        0x85: 'SLEEPING',
        0x87: 'AIRLOCK2',
        0x89: 'CONTROL',
        0x8B: 'AIRLOCK3',
        0x8D: 'LIBRARY1',
        0x93: 'AIRLOCK4',
        0x94: 'BOMBS',
        0x95: 'GAS',
        0x96: 'AIRLOCK5',
        0x97: 'BIO',
        0x98: 'AIRLOCK6',
        0x99: 'STORAGE',
    },
    8: {
        0x84: 'AIRLOCK7',
        0x86: 'GALLEY',
        0x88: 'AIRLOCK8',
        0x8A: 'RECREATION',
        0x8C: 'AIRLOCK9',
        0x8E: 'SICK_BAY',
        0x8F: 'AIRLOCK10',
        0x90: 'POWER',
        0x91: 'AIRLOCK11',
        0x92: 'ENGINES',
        0x9A: 'AIRLOCK12',
        0x9B: 'GUN',
        0x9C: 'WEAPONRY',
        0x9D: 'AIRLOCK13',
        0x9E: 'EXIT2',
    },
    9: {
        0x81: 'SURFACE',
        0x82: 'CARNEGIE',
        0x83: 'GRAND_CENTRAL',
        0x84: 'DISCO',
        0x85: 'MUSEUM',
        0x86: 'BIOLOGICAL',
        0x87: 'NURSERY',
        0x88: 'GREEN_HOUSE',
        0x89: 'LIBRARY2',
        0x8A: 'GENERATOR',
        0x8B: 'PITTSBURG',
        0x8C: 'DETROIT',     
    }
}

COMMANDS = {
    0x00: 'move_and_look',
    0x01: 'is_in_pack_or_room',
    0x02: 'is_owned_by',
    0x03: 'is_located',
    0x04: 'print_message',
    0x05: 'is_leq_last_random',
    0x06: 'print_inventory',
    0x07: 'print_room_description',
    0x08: 'is_noun1',
    0x09: 'is_noun2',
    0x0A: 'is_input_phrase',
    0x0B: 'switch',
    0x0C: 'fail',
    0x0D: 'group_AND',
    0x0E: 'group_OR',
    0x0F: 'pick_up_var_object',
    0x10: 'drop_var',
    0x11: 'print_noun1',
    0x12: 'print_noun2',
    0x13: 'process_phrase_by_room',
    0x14: 'reverse_status',
    0x15: 'is_var_attributes',
    0x16: 'print_var',
    0x17: 'move_object_to',
    0x18: 'is_var_owned_by_active',
    0x19: 'move_active_object',
    0x1A: 'set_var_to_noun1',
    0x1B: 'set_var_to_noun2',
    0x1C: 'set_var_object',
    0x1D: 'attack_var',
    0x1E: 'swap_object_locations',
    0x1F: 'print2',
    0x20: 'is_active_object',
    0x21: 'execute_phrase',
    0x22: 'is_less_equal_health',
    0x23: 'heal_var',
    0x24: 'exit_program',
    0x25: 'print_linefeed',
    0x26: 'print_score',
    0x27: 'load_game',
    0x28: 'save_game',
    0x29: 'toggle_open_VAR',
    0x2A: 'toggle_lock_VAR',
    0x2B: 'random',
    0x2C: 'set_active',
    0x2D: 'is_var_object',
    
    0x2E: 'is_var_ext_attributes',
    0x2F: 'load_section_from_disk',
    0x30: 'set_current_room',
    0x31: 'move_noun2_to_var_object',
    0x32: 'move_noun1_to_var_object',
    0x33: 'print_objects_on_var_object',
    0x34: 'save_system_objects_to_disk',
    0x35: 'load_system_objects_from_disk',
    0x36: 'is_in_room_or_open_container',
    0x37: 'is_player_in_an_object',
    0x38: 'bump_score',
    0x39: 'is_weight_70_or_less',
    0x3A: 'clear_screen',
    0x3B: 'wait_for_key123',
}

ROUTINES = {
    0x81: 'PRINT_DOOR_HERE',
    0x80: 'PRINT_SHOTGUN_HERE',    
    0x8B: 'PRINT_PERIOD',
    0x8D: 'IS_CLOSED',
    0x8F: 'GET_OBJECT',
    0x90: 'PRINT_ERROR_CLIMB_ENTER',
    0x91: 'PRINT_USE_DIRECTIONS',
    0x92: 'PRINT_TRIED_BUT_COULDNT',
    0x94: 'INITIALIZE_GAME',  # Moves to HIGHWAY_WEST in section 1
    0x95: 'PRINT_TRAIL_MEANDERS',
    0x96: 'PRINT_VAST_CANYON',
    0x97: 'PRINT_CERTAIN_DEATH',
    0x98: 'PRINT_LAKE',
    0x99: 'DIE_CANYON_PLUNGE',
    0x9A: 'PRINT_CANYON_PREVENTS',
    0x9B: 'PRINT_EMPTY_HIGHWAY',
    0x9C: 'PRINT_AIRLOCK_TWO_BUTTONS',
    0x9D: 'PRINT_EXIT_YELLOW_BUTTON',
    0x9E: 'REMOVE_OVAL_FROM_ROOM',
    0x9F: 'OVAL_YELLOW_BUTTON',
    0xA0: 'OVAL_RED_BUTTON',
    0xA1: 'OVAL_BLUE_BUTTON',
    0xA2: 'PRINT_ALREADY_HAVE_THE_var',
    0xA3: 'PRINT_WELCOME_MESSAGE',  # Moves to HIGHWAY_WEST in section 1
    0xA5: 'IS_OPEN',
    0xA6: 'OPEN',
    0xA8: 'PRINT_noun1',
    0xA9: 'PRINT_noun2',
    0xAA: 'PRINT_THE_var',
    0xAB: 'PRINT_STILL_IN_DESERT',
    0xAC: 'HANDLE_ORANGE_BUTTON',
    0xAD: 'HANDLE_OVAL',
    0xAE: 'PRINT_PUSH_BUTTON',
    0xAF: 'PRINT_I_SEE_NO_noun1_HERE',
    0xB0: 'PRINT_AIRLOCK_THREE_BUTTONS',
    0xB1: 'PRINT_var_CONTAINS',
    0xB2: 'PRINT_ON_var_CAN_BE_SEEN',
    0xB3: 'PRINT_DISK_ERROR',
    0xB4: 'PRINT_AND',
    0xB5: 'PRINT_BY_YOUR_COMMAND',
    0xB6: 'PRINT_TWO_SAME_SPACE',
    0xB7: 'PRINT_HAVE_TO_OPEN_var',
    0xB8: 'PRINT_GARBAGE_GAMES',
    0xB9: 'PRINT_JUKEBOX',
    0xBA: 'OPEN_UNLOCK',
    0xBB: 'PRINT_LOOK_IN_AT',
    0xBC: 'SHOOT_DROP_SHELL',
    0xBD: 'PRINT_SHAGGY_CREATURE',
    0xBE: 'PRINT_FORCE_FIELD',
    0xBF: 'IS_LIQUID_REACHABLE',
    0xC0: 'ARE_NOUNS_GIVEN',
    0xC1: 'PRINT_CANT_REACH_var',
    0xC2: 'PRINT_CANT_BUDGE_noun1',
    0xC3: 'IS_PLAYER_LACKING_WISDOM',
    0xC4: 'IS_PHRASE_AN_AFFECT',
    0xC5: 'ENTER_CLIMB_OUT',
    0xC6: 'PROMPT_FOR_DRIVE_NUMBER',
    0xC7: 'IS_OBJECT_RIBULN',
    0xC8: 'BACK_TO_TOWN',
    0xC9: 'PRINT_COMPLETED_PERCENT', 
    0xCA: 'DIE_ENERGY_BEAM',
}

OBJECTS = {
    0x00: "nothing",
    0x01: "PLAYER",

    0x02: "DOOR_GAS_STATION",
    0x03: "DOOR_FRONT_OF_STATION",
    0x04: "DOOR_EAST_OF_STATION",
    0x05: "DOOR_RESTROOM",
    0x06: "DOOR_MAIN_STREET_WEST",
    0x07: "DOOR_SALOON",
    0x08: "DOOR_MAIN_STREET_WEST",
    0x09: "DOOR_SHERIFFS_OFFICE",
    0x0A: "DOOR_HARDWARE_SOUTH",
    0x0B: "DOOR_TOWN_CENTER_SLIMS",
    0x0C: "DOOR_TOWN_CENTER_BOBS",
    0x0D: "DOOR_SLIMS_GROCERY",
    0x0E: "DOOR_MAIN_STREET_EAST_HOTEL",
    0x0F: "DOOR_HOTEL_LOBBY",
    0x10: "DOOR_MAIN_STREET_EAST_BANK",
    0x11: "DOOR_BANK",    
    0x12: "DOOR",
    0x13: "DOOR",
    0x14: "DOOR_COVERED_SHELTER",
    0x15: "DOOR_SHELTER",
    0x16: "RED_DOOR_HALLWAY",
    0x17: "DOOR_NORTH_ROOM",
    0x18: "BLUE_DOOR_HALLWAY",
    0x19: "DOOR_SOUTH_ROOM",

    0x1A: "MASTER_KEY",
    0x1B: "BRASS_KEY_SHERIFF",
    0x1C: "SKELETON_KEY",
    0x1D: "STEEL_KEY_BANK",
    0x1E: "RED_KEY_SLIMS",
    0x1F: "SMALL_KEY_CAB",
    
    0x20: "DESK",
    0x21: "TOP_DRAWER",
    0x22: "MIDDLE_DRAWER",
    0x23: "BOTTOM_DRAWER",
    0x24: "CROWBAR",
    0x25: "WANTED_POSTER",
    0x26: "GUN_CABINET",
    0x27: "SHOTGUN_IN_CABINET",
    0x28: "SHOTGUN",
    0x29: "SHOTGUN_SHELL1",
    0x2A: "SHOTGUN_SHELL2",
    0x2B: "GAS_PUMP",
    0x2C: "PADLOCK",
    0x2D: "JACK-O-MATIC",
    0x2E: "RUSTY_JEEP",
    0x2F: "FLAT_TIRE",
    0x30: "SPARE_TIRE",
    0x31: "SPHORX",
    0x32: "SHOVEL",
    0x33: "RATTLE_SNAKE",
    0x34: "DEAD_SNAKE",
    0x35: "SNAKE_VENOM",
    0x36: "FOOD",
    0x37: "STEEL_SAFE",
    0x38: "MONEY",
    0x39: "DYNAMITE",
    0x3A: "CONTROL_PANEL",
    0x3B: "RADIO",
    0x3C: "RADIO",
    0x3D: "BOTTLE",
    0x3E: "OVAL",
    0x3F: "YELLOW_BUTTON",
    0x40: "RED_BUTTON",
    0x41: "BLUE_BUTTON",
    0x42: "ORANGE_BUTTON",
    0x43: "BROWN_LIQUID",
    0x44: "BAR",
    0x45: "SINK",
    0x46: "WATER",
    0x47: "COUNTER",
    0x48: "DRESSER",
    0x49: "TABLE",
    0x4A: "HOOD",
    0x4B: "LIT_DYNAMITE_FUSE",
    0x4C: "BLASTED_SAFE",
    0x4D: "DOOR",
    0x4E: "BOULDER",
    0x4F: "RADIO",
    0x50: "DRESSER",
    0x51: "CHAIR",
    0x52: "CHAIR",
    0x53: "BED",
    0x54: "BED",
    0x55: "MOUND_SAND",
    0x56: "SIGN",
    0x57: "MESSAGE",
    0x58: "NEON_SIGN",
    0x59: "AQUARIUM",
    0x5A: "ENTRANCE_CLEAR",
    0x5B: "LIMIT_SIGN",
    0x5C: "PAIR_HANDS",
    0x5D: "BARRED_WINDOW_OUTSIDE",
    0x5E: "BARRED_WINDOW_INSIDE",
    0x5F: "SHELTER",
    0x60: "SHELTER",
    0x61: "GROUND",
    0x62: "SHAGGY_CREATURE",
    0x63: "GREY_CUBE",
    0x64: "WHITE_CUBE",
    0x65: "TABLE",
    0x66: "RECESS",
    0x67: "HOLE",
    0x68: "HOLE_BOULDERS",
    0x69: "PICTURE",
    0x6A: "GLASS_CYLINDER",
    0x6B: "WHITE_BUTTON_LIGHTS",
    0x6C: "MAROON_BUTTON",
    0x6D: "LIGHTS",
    0x6E: "CONSOLE",
    0x6F: "CHAIR",
    0x70: "WHITE_BUTTON_SCREEN",
    0x71: "GREEN_BUTTON_WEAPON",
    0x72: "VIEWING_SCREEN",
    0x73: "DISPLAY_EARTH",
    0x74: "DISPLAY_MOON",
    0x75: "DISPLAY_MOTHER_SHIP",
    0x76: "CHAIR",
    0x77: "HANDGRIP",
    0x78: "CHAIR",
    0x79: "LARGE_CUBE",
    0x7A: "HOLE_WISER",
    0x7B: "TABLE",
    0x7C: "TRANSPARENT_VIAL",
    0x7D: "TSOM_SOLUTION",
    0x7E: "PEDESTAL",
    0x7F: "TWO_INCH_HOLE",
    0x80: "WISDOM",
    0x81: "GREEN_CUBE",
    0x82: "ROD_WITH_SPHERE",
    0x83: "RADIATION_DOSE1",
    0x84: "RADIATION_DOSE2",
    0x85: "CYLINDER_BOMB",
    0x86: "CYLINDER_POISON",
    0x87: "CYLINDER_ANTS",
    0x88: "CYLINDERS_UNABLE",
    0x89: "ALIEN_ANTS",
    0x8A: "DEAD_ALIEN",
    0x8B: "SQUIRMING_ALIEN",
    0x8C: "PROSPECTOR",
    0x8D: "PROSPECTOR_HAS_SPOKEN",
    0x8E: "MACHINE",
    0x8F: "WHITE_BUTTON_ENGINES",
    0x90: "CHAIR",
    0x91: "ALIEN_POISON",
    0x92: "SCORE", 
    0x93: "DOOR_ESNEL",   
    0x94: "GOOLUB",
    0x95: "DOOR_ESNEL",
    0x96: "DOOR_ESNEL",
    0x97: "SMALL_UKORK_KEY",
    0x98: "BLURNUM_RADIO",
    0x99: "SHIP",
    0x9A: "WALL",
    # 0x9B
    0x9C: "SHIP",
    0x9D: 'THIRST_TRACKER',
}

EXT_ATTRIBUTES = {
    0x80: 'Glass',
    0x40: 'Locked',
    0x20: 'Closed',
    0x10: 'liQuid'
}

ATTRIBUTES = {
    0x80: '??',
    0x40: 'Weapon',
    0x20: 'Portable',
    0x10: 'Alive',
    0x08: 'Openable',
    0x04: 'Readable',
    0x02: 'Holder',
    0x01: 'Surface'
}

def get_ext_attribute_name(value):
    ret_bits = ''
    ret_words = []
    for bit, name in EXT_ATTRIBUTES.items():
        if value & bit:
            for p in name:
                if p=='?' or p.isupper():
                    ret_bits += p
                    break
            ret_words.append(name)
        else:
            ret_bits += '.'
    return f'{ret_bits}----({",".join(ret_words)})'

def get_attribute_name(value):
    # attributes=?QW.S...(liQuid, Weapon, Surface)
    ret_bits = ''
    ret_words = []
    for bit, name in ATTRIBUTES.items():
        if value & bit:
            for p in name:
                if p=='?' or p.isupper():
                    ret_bits += p
                    break
            ret_words.append(name)
        else:
            ret_bits += '.'
    return f'{ret_bits}({",".join(ret_words)})'

def check_unique_rooms():
    names = []
    for rooms in ROOMS.values():
        for name in rooms.values():
            if name in names:
                print(f'Duplicate room name: {name}')
            else:
                names.append(name)
    names = []
    for rooms in ROOMS.values():
        for name in rooms.values():
            names.append(name)
    names.sort()
    for name in names:
        print(name)

# check_unique_rooms()

def get_section_name(section):
    return f'SECTION_{section:02X}_{SECTIONS[section]}'

def get_room_name(section, room):
    disk_section = ROOMS[section]
    if room not in disk_section:
        return f'RM_{section}_{room:02X}_??'
    name = disk_section[room]
    return f'RM_{section}_{name}'

def get_command_name(command):
    return f'COM_{command:02X}_{COMMANDS[command]}'

def get_routine_name(routine):
    if routine not in ROUTINES:
        return f'FN_{routine:02X}_??'
    return f'FN_{routine:02X}_{ROUTINES[routine]}'

def get_object_name(object):
    if object==0:
        return 'nothing'
    if object not in OBJECTS:
        return f'OBJ_{object:02X}_??'
    return f'OBJ_{object:02X}_{OBJECTS[object]}'

def get_destination(section, room_num):
        
        if room_num==0:
            return 'nowhere'        
        
        if room_num>=0x80:
            return get_room_name(section, room_num)
        else:
            return get_object_name(room_num)
        
    