# http://www.keil.com/support/man/docs/is51/is51_opcodes.htm

OPCODES = [
    {"mnem": "NOP", "code": "00", "bus": ""},
    {"mnem": "AJMP p", "code": "01pp", "bus": "x"},
    {"mnem": "LJMP t", "code": "02tmtl", "bus": "x"},
    {"mnem": "RR A", "code": "03", "bus": ""},
    {"mnem": "INC A", "code": "04", "bus": ""},
    {"mnem": "INC p", "code": "05pp", "bus": ""},
    {"mnem": "INC @R0", "code": "06", "bus": ""},
    {"mnem": "INC @R1", "code": "07", "bus": ""},
    {"mnem": "INC R0", "code": "08", "bus": ""},
    {"mnem": "INC R1", "code": "09", "bus": ""},
    {"mnem": "INC R2", "code": "0A", "bus": ""},
    {"mnem": "INC R3", "code": "0B", "bus": ""},
    {"mnem": "INC R4", "code": "0C", "bus": ""},
    {"mnem": "INC R5", "code": "0D", "bus": ""},
    {"mnem": "INC R6", "code": "0E", "bus": ""},
    {"mnem": "INC R7", "code": "0F", "bus": ""},
    {"mnem": "JBC b,r", "code": "10bbrr", "bus": "x"},
    {"mnem": "ACALL p", "code": "11pp", "bus": "x"},
    {"mnem": "LCALL t", "code": "12tmtl", "bus": "x"},
    {"mnem": "RRC A", "code": "13", "bus": ""},
    {"mnem": "DEC A", "code": "14", "bus": ""},
    {"mnem": "DEC p", "code": "15", "bus": ""},
    {"mnem": "DEC @R0", "code": "16", "bus": ""},
    {"mnem": "DEC @R1", "code": "17", "bus": ""},
    {"mnem": "DEC R0", "code": "18", "bus": ""},
    {"mnem": "DEC R1", "code": "19", "bus": ""},
    {"mnem": "DEC R2", "code": "1A", "bus": ""},
    {"mnem": "DEC R3", "code": "1B", "bus": ""},
    {"mnem": "DEC R4", "code": "1C", "bus": ""},
    {"mnem": "DEC R5", "code": "1D", "bus": ""},
    {"mnem": "DEC R6", "code": "1E", "bus": ""},
    {"mnem": "DEC R7", "code": "1F", "bus": ""},
    {"mnem": "JB b,r", "code": "20bbrr", "bus": "x"},
    {"mnem": "AJMP p", "code": "21pp", "bus": "x"},
    {"mnem": "RET", "code": "22", "bus": ""},
    {"mnem": "RL A", "code": "23", "bus": ""},
    {"mnem": "ADD A,b", "code": "24bb", "bus": ""},
    {"mnem": "ADD A,p", "code": "25pp", "bus": ""},
    {"mnem": "ADD A,@R0", "code": "26", "bus": ""},
    {"mnem": "ADD A,@R1", "code": "27", "bus": ""},
    {"mnem": "ADD A,R0", "code": "28", "bus": ""},
    {"mnem": "ADD A,R1", "code": "29", "bus": ""},
    {"mnem": "ADD A,R2", "code": "2A", "bus": ""},
    {"mnem": "ADD A,R3", "code": "2B", "bus": ""},
    {"mnem": "ADD A,R4", "code": "2C", "bus": ""},
    {"mnem": "ADD A,R5", "code": "2D", "bus": ""},
    {"mnem": "ADD A,R6", "code": "2E", "bus": ""},
    {"mnem": "ADD A,R7", "code": "2F", "bus": ""},
    {"mnem": "JNB b,r", "code": "30bbrr", "bus": "x"},
    {"mnem": "ACALL p", "code": "31pp", "bus": ""},
    {"mnem": "RETI", "code": "32", "bus": ""},
    {"mnem": "RLC A", "code": "33", "bus": ""},
    {"mnem": "ADDC A,b", "code": "34bb", "bus": ""},
    {"mnem": "ADDC A,p", "code": "35pp", "bus": ""},
    {"mnem": "ADDC A,@R0", "code": "36", "bus": ""},
    {"mnem": "ADDC A,@R1", "code": "37", "bus": ""},
    {"mnem": "ADDC A,R0", "code": "38", "bus": ""},
    {"mnem": "ADDC A,R1", "code": "39", "bus": ""},
    {"mnem": "ADDC A,R2", "code": "3A", "bus": ""},
    {"mnem": "ADDC A,R3", "code": "3B", "bus": ""},
    {"mnem": "ADDC A,R4", "code": "3C", "bus": ""},
    {"mnem": "ADDC A,R5", "code": "3D", "bus": ""},
    {"mnem": "ADDC A,R6", "code": "3E", "bus": ""},
    {"mnem": "ADDC A,R7", "code": "3F", "bus": ""},
    {"mnem": "JC r", "code": "40rr", "bus": "x"},
    {"mnem": "AJMP p", "code": "41pp", "bus": "x"},
    {"mnem": "ORL p,A", "code": "42pp", "bus": ""},
    {"mnem": "ORL p,b", "code": "43ppbb", "bus": ""},
    {"mnem": "ORL A,b", "code": "44bb", "bus": ""},
    {"mnem": "ORL A,p", "code": "45pp", "bus": ""},
    {"mnem": "ORL A,@R0", "code": "46", "bus": ""},
    {"mnem": "ORL A,@R1", "code": "47", "bus": ""},
    {"mnem": "ORL A,R0", "code": "48", "bus": ""},
    {"mnem": "ORL A,R1", "code": "49", "bus": ""},
    {"mnem": "ORL A,R2", "code": "4A", "bus": ""},
    {"mnem": "ORL A,R3", "code": "4B", "bus": ""},
    {"mnem": "ORL A,R4", "code": "4C", "bus": ""},
    {"mnem": "ORL A,R5", "code": "4D", "bus": ""},
    {"mnem": "ORL A,R6", "code": "4E", "bus": ""},
    {"mnem": "ORL A,R7", "code": "4F", "bus": ""},
    {"mnem": "JNC r", "code": "50rr", "bus": ""},
    {"mnem": "ACALL p", "code": "51pp", "bus": ""},
    {"mnem": "ANL p,A", "code": "52pp", "bus": ""},
    {"mnem": "ANL p,b", "code": "53ppbb", "bus": ""},
    {"mnem": "ANL A,b", "code": "54bb", "bus": ""},
    {"mnem": "ANL A,p", "code": "55pp", "bus": ""},
    {"mnem": "ANL @R0", "code": "56", "bus": ""},
    {"mnem": "ANL @R1", "code": "57", "bus": ""},
    {"mnem": "ANL A,R0", "code": "58", "bus": ""},
    {"mnem": "ANL A,R1", "code": "59", "bus": ""},
    {"mnem": "ANL A,R2", "code": "5A", "bus": ""},
    {"mnem": "ANL A,R3", "code": "5B", "bus": ""},
    {"mnem": "ANL A,R4", "code": "5C", "bus": ""},
    {"mnem": "ANL A,R5", "code": "5D", "bus": ""},
    {"mnem": "ANL A,R6", "code": "5E", "bus": ""},
    {"mnem": "ANL A,R7", "code": "5F", "bus": ""},
    {"mnem": "JZ r", "code": "60rr", "bus": ""},
    {"mnem": "AJMP p", "code": "61pp", "bus": ""},
    {"mnem": "XRL p,A", "code": "62pp", "bus": ""},
    {"mnem": "XRL p,b", "code": "63ppbb", "bus": ""},
    {"mnem": "XRL A,b", "code": "64bb", "bus": ""},
    {"mnem": "XRL A,p", "code": "65pp", "bus": ""},
    {"mnem": "XRL A,@R0", "code": "66", "bus": ""},
    {"mnem": "XRL A,@R1", "code": "67", "bus": ""},
    {"mnem": "XRL A,R0", "code": "68", "bus": ""},
    {"mnem": "XRL A,R1", "code": "69", "bus": ""},
    {"mnem": "XRL A,R2", "code": "6A", "bus": ""},
    {"mnem": "XRL A,R3", "code": "6B", "bus": ""},
    {"mnem": "XRL A,R4", "code": "6C", "bus": ""},
    {"mnem": "XRL A,R5", "code": "6D", "bus": ""},
    {"mnem": "XRL A,R6", "code": "6E", "bus": ""},
    {"mnem": "XRL A,R7", "code": "6F", "bus": ""},
    {"mnem": "JNZ r", "code": "70rr", "bus": ""},
    {"mnem": "ACALL p", "code": "71pp", "bus": ""},
    {"mnem": "ORL C,b", "code": "72bb", "bus": ""},
    {"mnem": "JMP @A+DPTR", "code": "73", "bus": ""},
    {"mnem": "MOV A,b", "code": "74bb", "bus": ""},
    {"mnem": "MOV p,b", "code": "75ppbb", "bus": ""},
    {"mnem": "MOV @R0,b", "code": "76bb", "bus": ""},
    {"mnem": "MOV @R1,b", "code": "77bb", "bus": ""},
    {"mnem": "MOV R0,b", "code": "78bb", "bus": ""},
    {"mnem": "MOV R1,b", "code": "79bb", "bus": ""},
    {"mnem": "MOV R2,b", "code": "7Abb", "bus": ""},
    {"mnem": "MOV R3,b", "code": "7Bbb", "bus": ""},
    {"mnem": "MOV R4,b", "code": "7Cbb", "bus": ""},
    {"mnem": "MOV R5,b", "code": "7Dbb", "bus": ""},
    {"mnem": "MOV R6,b", "code": "7Ebb", "bus": ""},
    {"mnem": "MOV R7,b", "code": "7Fbb", "bus": ""},

    {"mnem": "SJMP", "code": "80", "bus": ""},
    {"mnem": "AJMP", "code": "81", "bus": ""},
    {"mnem": "ANL", "code": "82", "bus": ""},
    {"mnem": "MOVC", "code": "83", "bus": ""},
    {"mnem": "DIV", "code": "84", "bus": ""},
    {"mnem": "MOV", "code": "85", "bus": ""},
    {"mnem": "MOV", "code": "86", "bus": ""},
    {"mnem": "MOV", "code": "87", "bus": ""},
    {"mnem": "MOV", "code": "88", "bus": ""},
    {"mnem": "MOV", "code": "89", "bus": ""},
    {"mnem": "MOV", "code": "8A", "bus": ""},
    {"mnem": "MOV", "code": "8B", "bus": ""},
    {"mnem": "MOV", "code": "8C", "bus": ""},
    {"mnem": "MOV", "code": "8D", "bus": ""},
    {"mnem": "MOV", "code": "8E", "bus": ""},
    {"mnem": "MOV", "code": "8F", "bus": ""},
    {"mnem": "MOV", "code": "90", "bus": ""},
    {"mnem": "ACALL", "code": "91", "bus": ""},
    {"mnem": "MOV", "code": "92", "bus": ""},
    {"mnem": "MOVC", "code": "93", "bus": ""},
    {"mnem": "SUBB", "code": "94", "bus": ""},
    {"mnem": "SUBB", "code": "95", "bus": ""},
    {"mnem": "SUBB", "code": "96", "bus": ""},
    {"mnem": "SUBB", "code": "97", "bus": ""},
    {"mnem": "SUBB", "code": "98", "bus": ""},
    {"mnem": "SUBB", "code": "99", "bus": ""},
    {"mnem": "SUBB", "code": "9A", "bus": ""},
    {"mnem": "SUBB", "code": "9B", "bus": ""},
    {"mnem": "SUBB", "code": "9C", "bus": ""},
    {"mnem": "SUBB", "code": "9D", "bus": ""},
    {"mnem": "SUBB", "code": "9E", "bus": ""},
    {"mnem": "SUBB", "code": "9F", "bus": ""},
    {"mnem": "ORL", "code": "A0", "bus": ""},
    {"mnem": "AJMP", "code": "A1", "bus": ""},
    {"mnem": "MOV", "code": "A2", "bus": ""},
    {"mnem": "INC", "code": "A3", "bus": ""},
    {"mnem": "MUL", "code": "A4", "bus": ""},
    {"mnem": "?", "code": "A5", "bus": ""},
    {"mnem": "MOV", "code": "A6", "bus": ""},
    {"mnem": "MOV", "code": "A7", "bus": ""},
    {"mnem": "MOV", "code": "A8", "bus": ""},
    {"mnem": "MOV", "code": "A9", "bus": ""},
    {"mnem": "MOV", "code": "AA", "bus": ""},
    {"mnem": "MOV", "code": "AB", "bus": ""},
    {"mnem": "MOV", "code": "AC", "bus": ""},
    {"mnem": "MOV", "code": "AD", "bus": ""},
    {"mnem": "MOV", "code": "AE", "bus": ""},
    {"mnem": "MOV", "code": "AF", "bus": ""},
    {"mnem": "ANL", "code": "B0", "bus": ""},
    {"mnem": "ACALL", "code": "B1", "bus": ""},
    {"mnem": "CPL", "code": "B2", "bus": ""},
    {"mnem": "CPL", "code": "B3", "bus": ""},
    {"mnem": "CJNE", "code": "B4", "bus": ""},
    {"mnem": "CJNE", "code": "B5", "bus": ""},
    {"mnem": "CJNE", "code": "B6", "bus": ""},
    {"mnem": "CJNE", "code": "B7", "bus": ""},
    {"mnem": "CJNE", "code": "B8", "bus": ""},
    {"mnem": "CJNE", "code": "B9", "bus": ""},
    {"mnem": "CJNE", "code": "BA", "bus": ""},
    {"mnem": "CJNE", "code": "BB", "bus": ""},
    {"mnem": "CJNE", "code": "BC", "bus": ""},
    {"mnem": "CJNE", "code": "BD", "bus": ""},
    {"mnem": "CJNE", "code": "BE", "bus": ""},
    {"mnem": "CJNE", "code": "BF", "bus": ""},
    {"mnem": "PUSH", "code": "C0", "bus": ""},
    {"mnem": "AJMP", "code": "C1", "bus": ""},
    {"mnem": "CLR", "code": "C2", "bus": ""},
    {"mnem": "CLR", "code": "C3", "bus": ""},
    {"mnem": "SWAP", "code": "C4", "bus": ""},
    {"mnem": "XCH", "code": "C5", "bus": ""},
    {"mnem": "XCH", "code": "C6", "bus": ""},
    {"mnem": "XCH", "code": "C7", "bus": ""},
    {"mnem": "XCH", "code": "C8", "bus": ""},
    {"mnem": "XCH", "code": "C9", "bus": ""},
    {"mnem": "XCH", "code": "CA", "bus": ""},
    {"mnem": "XCH", "code": "CB", "bus": ""},
    {"mnem": "XCH", "code": "CC", "bus": ""},
    {"mnem": "XCH", "code": "CD", "bus": ""},
    {"mnem": "XCH", "code": "CE", "bus": ""},
    {"mnem": "XCH", "code": "CF", "bus": ""},
    {"mnem": "POP", "code": "D0", "bus": ""},
    {"mnem": "ACALL", "code": "D1", "bus": ""},
    {"mnem": "SETB", "code": "D2", "bus": ""},
    {"mnem": "SETB", "code": "D3", "bus": ""},
    {"mnem": "DA", "code": "D4", "bus": ""},
    {"mnem": "DJNZ", "code": "D5", "bus": ""},
    {"mnem": "XCHD", "code": "D6", "bus": ""},
    {"mnem": "XCHD", "code": "D7", "bus": ""},
    {"mnem": "DJNZ", "code": "D8", "bus": ""},
    {"mnem": "DJNZ", "code": "D9", "bus": ""},
    {"mnem": "DJNZ", "code": "DA", "bus": ""},
    {"mnem": "DJNZ", "code": "DB", "bus": ""},
    {"mnem": "DJNZ", "code": "DC", "bus": ""},
    {"mnem": "DJNZ", "code": "DD", "bus": ""},
    {"mnem": "DJNZ", "code": "DE", "bus": ""},
    {"mnem": "DJNZ", "code": "DF", "bus": ""},
    {"mnem": "MOVX", "code": "E0", "bus": ""},
    {"mnem": "AJMP", "code": "E1", "bus": ""},
    {"mnem": "MOVX", "code": "E2", "bus": ""},
    {"mnem": "MOVX", "code": "E3", "bus": ""},
    {"mnem": "CLR", "code": "E4", "bus": ""},
    {"mnem": "MOV", "code": "E5", "bus": ""},
    {"mnem": "MOV", "code": "E6", "bus": ""},
    {"mnem": "MOV", "code": "E7", "bus": ""},
    {"mnem": "MOV", "code": "E8", "bus": ""},
    {"mnem": "MOV", "code": "E9", "bus": ""},
    {"mnem": "MOV", "code": "EA", "bus": ""},
    {"mnem": "MOV", "code": "EB", "bus": ""},
    {"mnem": "MOV", "code": "EC", "bus": ""},
    {"mnem": "MOV", "code": "ED", "bus": ""},
    {"mnem": "MOV", "code": "EE", "bus": ""},
    {"mnem": "MOV", "code": "EF", "bus": ""},
    {"mnem": "MOVX", "code": "F0", "bus": ""},
    {"mnem": "ACALL", "code": "F1", "bus": ""},
    {"mnem": "MOVX", "code": "F2", "bus": ""},
    {"mnem": "MOVX", "code": "F3", "bus": ""},
    {"mnem": "CPL", "code": "F4", "bus": ""},
    {"mnem": "MOV", "code": "F5", "bus": ""},
    {"mnem": "MOV", "code": "F6", "bus": ""},
    {"mnem": "MOV", "code": "F7", "bus": ""},
    {"mnem": "MOV", "code": "F8", "bus": ""},
    {"mnem": "MOV", "code": "F9", "bus": ""},
    {"mnem": "MOV", "code": "FA", "bus": ""},
    {"mnem": "MOV", "code": "FB", "bus": ""},
    {"mnem": "MOV", "code": "FC", "bus": ""},
    {"mnem": "MOV", "code": "FD", "bus": ""},
    {"mnem": "MOV", "code": "FE", "bus": ""},
    {"mnem": "MOV", "code": "FF", "bus": ""},
]
