C  USE THIS TO GET THE RESPONSE TO GET INTO WIZARD MODE

      PROGRAM WIZARD
      IMPLICIT INTEGER(A-Z)
      CHARACTER*5 WORD,SCR1,SCR2,SCR3
      DIMENSION VAL(5)

C  CHANGE THIS IF YOU CHANGE IT IN THE GAME
      MAGNM=11111

      CALL GETIN(WORD,SCR1,SCR2,SCR3)
      DO 1 I=1,5
1       VAL(I)=ICHAR(WORD(I:I))-ICHAR('@')
      WORD='@@@@@'
      CALL DATIME(D,T)
      T=(T/60)*40+(T/10)*10
      D=MAGNM
      DO 19 Y=1,5
      Z=MOD(Y,5)+1
      X=MOD(IABS(VAL(Y)-VAL(Z))*MOD(D,10)+MOD(T,10),26)+1
      T=T/10
      D=D/10
19    WORD(Y:Y)=CHAR(ICHAR(WORD(Y:Y))+X)

      WRITE(*,*)WORD

      END


      SUBROUTINE DATIME(D,T)

C  RETURN THE DATE AND TIME IN D AND T.  D IS NUMBER OF DAYS SINCE 01-JAN-77,
C  T IS MINUTES PAST MIDNIGHT.  THIS IS HARDER THAN IT SOUNDS, BECAUSE THE
C  FINAGLED DEC FUNCTIONS RETURN THE VALUES ONLY AS ASCII STRINGS!

C  PORTING NOTE: THE CODE HERE IS A COMPLETE REWRITE OF THE ORIGINAL.
C  THERE IS NO PORTABLE WAY TO DO THIS, BUT THIS WAY WORKS FOR G77 AND
C  WILL PROBABLY WORK ON OTHER UNIX FORTRAN IMPLEMENTATIONS.

      IMPLICIT INTEGER(A-Z)
      INTRINSIC TIME,LTIME
      DIMENSION TAR(9)
      CALL LTIME(TIME(),TAR)
      Y=TAR(6)-77
C  WILL BREAK IN 2101
      LEAP=Y/4
      D=Y*365+LEAP+TAR(8)
      T=TAR(3)*60+TAR(2)
      END


      SUBROUTINE GETIN(WORD1,WORD1X,WORD2,WORD2X)
      IMPLICIT INTEGER(A-Z)
      CHARACTER*5 A,WORD1,WORD1X,WORD2,WORD2X
      DIMENSION A(6)
      DATA A/6*'     '/

2     READ(*,3)(A(I),I=1,4)
3     FORMAT(4A5)
      J=0
      DO 9 I=1,4
      IF(A(I).NE.A(6))J=1
9     CALL UPCASE(A(I))
      IF(J.EQ.0)GOTO 2

      SECOND=0
      WORD1=A(1)
      WORD1X=A(2)
      WORD2=A(6)
      DO 10 J=1,4
      DO 10 K=1,5
      IF (A(J)(K:K).EQ.' ')GOTO 15
      IF(SECOND.EQ.0)GOTO 10
      WORD2=A(J)(K:)
      WORD2X=A(J+1)(K:)
      IF(K.NE.1)THEN
        WORD2(7-K:)=A(J+1)
        WORD2X(7-K:)=A(J+2)
      ENDIF
      RETURN
15    IF(SECOND.EQ.1)GOTO 10
      SECOND=1
      IF(J.EQ.1)WORD1(K:)=A(6)
10    CONTINUE
      RETURN
      END

      SUBROUTINE UPCASE(S)
      CHARACTER*5 S
      DO 1 I=1,5
1       IF(S(I:I).GE.'a'.AND.S(I:I).LE.'z')
       1 S(I:I)=CHAR(ICHAR(S(I:I))-32)
      END

